linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - revive
    - gofmt

linters-settings:
  errcheck:
    exclude-functions:
      - (*go.uber.org/zap.Logger).Sync
