linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - revive
    - gofmt

linters-settings:
  errcheck:
    exclude-functions:
      - dev/errcheck-exclude.txt
