version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - revive
  settings:
    errcheck:
      exclude-functions:
        - (*go.uber.org/zap.Logger).Sync
  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    warn-unused: true
