docPath: docs/dbSchema
er:
  format: mermaid

lint:
  requireTableComment:
    enabled: true
  requireColumnComment:
    enabled: true
    exclude:
      - id
      - created_at
      - updated_at
      - deleted_at

relations:
  - table: users
    columns:
      - icon
    parentTable: files
    parentColumns:
      - id
  - table: channels
    columns:
      - creator_id
      - updater_id
    parentTable: users
    parentColumns:
      - id
  - table: channels
    columns:
      - parent_id
    parentTable: channels
    parentColumns:
      - id
  - table: stamps
    columns:
      - creator_id
    parentTable: users
    parentColumns:
      - id

comments:
  - table: users
    tableComment: ユーザーテーブル
    columnComments:
      id: ユーザーUUID
      name: traP ID
      display_name: 表示名
      password: ハッシュ化されたパスワード
      salt: パスワードソルト
      icon: アイコンファイルUUID
      status: アカウント状態
      bot: BOTユーザーかどうか
      role: ユーザーロール
      created_at: 作成日時
      updated_at: 更新日時
  - table: user_profiles
    tableComment: ユーザープロフィールテーブル
    columnComments:
      user_id: ユーザーUUID
      bio: bio
      twitter_id: Twitter ID
      last_online: 最終オンライン日時
      home_channel: ホームチャンネルUUID
      updated_at: 更新日時
  - table: channels
    tableComment: チャンネルテーブル
    columnComments:
      id: チャンネルUUID
      name: チャンネル名
      parent_id: 親チャンネルUUID
      topic: チャンネルトピック
      is_forced: 強制通知チャンネルかどうか
      is_public: 公開チャンネルかどうか
      is_visible: 可視チャンネルかどうか
      creator_id: チャンネル作成者UUID
      updater_id: チャンネル更新者UUID
      created_at: チャンネル作成日時
      updated_at: チャンネル更新日時
      deleted_at: チャンネル削除日時
  - table: messages
    tableComment: メッセージテーブル
    columnComments:
      id: メッセージUUID
      user_id: 投稿ユーザーUUID
      channel_id: 投稿先チャンネルUUID
      text: 本文
      created_at: 作成日時
      updated_at: 更新日時
      deleted_at: 削除日時
  - table: archived_messages
    tableComment: アーカイブ化されたメッセージのテーブル(編集前メッセージ)
    columnComments:
      id: アーカイブUUID
      message_id: 元のメッセージUUID
      user_id: 投稿ユーザーUUID
      text: 本文
      date_time: 本文の投稿日時
  - table: stars
    tableComment: お気に入りチャンネルテーブル
    columnComments:
      user_id: ユーザーUUID
      channel_id: チャンネルUUID
  - table: users_private_channels
    tableComment: プライベートチャンネル参加者テーブル
    columnComments:
      user_id: ユーザーUUID
      channel_id: チャンネルUUID
  - table: users_subscribe_channels
    tableComment: チャンネル購読者テーブル
    columnComments:
      user_id: ユーザーUUID
      channel_id: チャンネルUUID
      mark: 未読管理が有効かどうか
      notify: 通知が有効かどうか
  - table: unreads
    tableComment: メッセージ未読テーブル
    columnComments:
      user_id: ユーザーUUID
      channel_id: チャンネルUUID
      message_id: メッセージUUID
      noticeable: 注目メッセージかどうか
      message_created_at: 未読日時
  - table: users_tags
    tableComment: ユーザータグテーブル
    columnComments:
      user_id: ユーザーUUID
      tag_id: タグUUID
      is_locked: ロックされているかどうか
      created_at: 作成日時
      updated_at: 更新日時
  - table: tags
    tableComment: タグテーブル
    columnComments:
      id: タグUUID
      name: タグ文字列
      created_at: 作成日時
      updated_at: 更新日時
  - table: stamps
    tableComment: スタンプテーブル
    columnComments:
      id: スタンプUUID
      name: スタンプ名
      creator_id: 作成者UUID
      file_id: ファイルUUID
      is_unicode: Unicode絵文字かどうか
      created_at: 作成日時
      updated_at: 更新日時
      deleted_at: 削除日時
  - table: stamp_palettes
    tableComment: スタンプパレットテーブル
    columnComments:
      id: スタンプパレットUUID
      name: スタンプパレット名
      description: スタンプパレットの説明
      stamps: スタンプUUID配列の文字列
      creator_id: 作成者UUID
      created_at: 作成日時
      updated_at: 更新日時
  - table: messages_stamps
    tableComment: メッセージスタンプテーブル
    columnComments:
      message_id: メッセージUUID
      stamp_id: スタンプUUID
      user_id: ユーザーUUID
      count: スタンプ数
      created_at: 作成日時
      updated_at: 更新日時
  - table: devices
    tableComment: FCMデバイステーブル
    columnComments:
      token: FCMデバイストークン
      user_id: ユーザーUUID
      created_at: 作成日時
  - table: dm_channel_mappings
    tableComment: DMチャンネルマッピングテーブル
    columnComments:
      channel_id: チャンネルUUID
      user1: ユーザーUUID
      user2: ユーザーUUID
  - table: migrations
    tableComment: gormigrate用のデータベースバージョンテーブル
  - table: bot_event_logs
    tableComment: BOTイベントログテーブル
    columnComments:
      request_id: リクエストID
      bot_id: BOT UUID
      event: イベント名
      body: イベント内容(jsonテキストが格納)
      error: エラー内容
      result: イベント配送結果
      code: HTTP Modeの場合HTTPステータスコード
      latency: リクエスト時間
      date_time: イベント発生日時
  - table: bot_join_channels
    tableComment: BOT参加チャンネルテーブル
    columnComments:
      bot_id: BOT UUID
      channel_id: チャンネルUUID
  - table: bots
    tableComment: traQ BOTテーブル
    columnComments:
      bot_user_id: BOTユーザーUUID
      description: BOT説明
      verification_token: 認証トークン
      access_token_id: BOTアクセストークンID
      mode: BOT動作モード
      post_url: BOTサーバーエンドポイント(HTTP Mode)
      subscribe_events: BOTが購読しているイベントリスト(スペース区切り)
      privileged: 特権BOTかどうか
      state: BOTの状態
      bot_code: BOTコード
      creator_id: BOT制作者UUID
  - table: channel_events
    tableComment: チャンネルイベントテーブル
    columnComments:
      event_id: イベントID
      channel_id: チャンネルUUID
      event_type: イベントタイプ
      detail: イベント詳細(jsonテキストが格納)
      date_time: イベント発生日時
  - table: channel_latest_messages
    tableComment: チャンネル最新メッセージテーブル
    columnComments:
      channel_id: チャンネルUUID
      message_id: メッセージUUID
      date_time: メッセージ作成日時
  - table: files
    tableComment: ファイルテーブル
    columnComments:
      name: ファイル名
      mime: ファイルMIMEタイプ
      size: ファイルサイズ(byte)
      creator_id: ファイル作成者UUID
      hash: MD5ハッシュ
      type: ファイルタイプ
      is_animated_image: アニメーション画像かどうか
      channel_id: 所属チャンネルUUID
  - table: files_thumbnails
    tableComment: ファイルサムネイルテーブル
    columnComments:
      file_id: ファイルUUID
      type: サムネイルタイプ
      mime: MIMEタイプ
      width: 画像の幅
      height: 画像の高さ
  - table: files_acl
    tableComment: ファイルアクセスコントロールリストテーブル
    columnComments:
      file_id: ファイルUUID
      user_id: ユーザーUUID
      allow: 許可
  - table: message_reports
    tableComment: メッセージ通報テーブル
    columnComments:
      message_id: メッセージUUID
      reporter: 通報者UUID
      reason: 通報理由
  - table: pins
    tableComment: ピンテーブル
    columnComments:
      message_id: メッセージUUID
      user_id: ピンしたユーザーUUID
  - table: webhook_bots
    tableComment: traQ Webhookテーブル
    columnComments:
      bot_user_id: WebhookユーザーUUID
      description: 説明
      secret: BOTシークレット
      channel_id: デフォルト投稿先チャンネルUUID
      creator_id: 作成者UUID
  - table: user_group_members
    tableComment: ユーザーグループメンバーテーブル
    columnComments:
      group_id: グループUUID
      user_id: ユーザーUUID
      role: 役割
  - table: user_group_admins
    tableComment: ユーザーグループ管理者テーブル
    columnComments:
      group_id: グループUUID
      user_id: ユーザーUUID
  - table: user_groups
    tableComment: ユーザーグループテーブル
    columnComments:
      name: グループ名
      description: グループ説明
      type: グループタイプ
      icon: アイコンファイルUUID
  - table: user_roles
    tableComment: ユーザーロールテーブル
    columnComments:
      name: ロール名
      oauth2_scope: OAuth2のスコープかどうか
      system: 組み込みロールかどうか
  - table: user_role_permissions
    tableComment: ユーザーロールパーミッションテーブル
    columnComments:
      role: ロール名
      permission: パーミッション名
  - table: user_role_inheritances
    tableComment: ユーザーロール継承テーブル
    columnComments:
      role: ロール名
      sub_role: サブロール名
  - table: r_sessions
    tableComment: traQ API HTTPセッションテーブル
    columnComments:
      token: セッショントークン
      reference_id: 参照ID
      user_id: セッションがログインしているユーザーUUID
      data: セッションデータ(gobバイナリ)
      created: 生成日時
  - table: oauth2_authorizes
    tableComment: OAuth2認可リクエストテーブル
    columnComments:
      code: 認可コード
      client_id: クライアントID
      user_id: リクエストユーザーUUID
      expires_in: 有効秒
      redirect_uri: リダイレクトURI
      scopes: 認可対象スコープ
      original_scopes: 元の要求スコープ
      code_challenge: PKCEコードチャレンジ
      code_challenge_method: PKCEコードチャレンジ方式
      nonce: nonce
  - table: oauth2_clients
    tableComment: OAuth2クライアントテーブル
    columnComments:
      name: クライアント名
      description: 説明
      confidential: コンフィデンシャルかどうか
      creator_id: 作成者UUID
      secret: クライアントシークレット
      redirect_uri: リダイレクトURI
      scopes: スコープ
  - table: oauth2_tokens
    tableComment: OAuth2トークンテーブル
    columnComments:
      client_id: クライアントID
      user_id: ユーザーUUID
      redirect_uri: リダイレクトURI
      access_token: アクセストークン
      refresh_token: リフレッシュトークン
      refresh_enabled: リフレッシュトークンが有効かどうか
      scopes: スコープ
      expires_in: 有効秒
  - table: clip_folders
    tableComment: クリップフォルダーテーブル
    columnComments:
      id: クリップフォルダーID
      name: クリップフォルダー名
      description: 説明
      owner_id: 所有者のUUID
      created_at: 作成日時
  - table: clip_folder_messages
    tableComment: クリップフォルダーメッセージテーブル
    columnComments:
      folder_id: クリップフォルダーID
      message_id: メッセージID
      created_at: クリップされた日時
  - table: soundboard_items
    tableComment: サウンドボードアイテムテーブル
    columnComments:
      name: アイテム名
      stamp_id: スタンプUUID
      creator_id: アイテム作成者UUID
  - table: external_provider_users
    tableComment: 外部認証ユーザーテーブル
    columnComments:
      user_id: ユーザーUUID
      provider_name: 認証プロバイダ名
      external_id: 認証プロバイダ上でのID
      extra: 追加データ
  - table: ogp_cache
    tableComment: OGPキャッシュテーブルr
    columnComments:
      url: 対象ページのURL
      url_hash: URLのSHA-1ハッシュ
      valid: ネガティブキャッシュでないか
      content: キャッシュ内容
      expires_at: 有効期限
  - table: user_settings
    tableComment: ユーザー設定
    columnComments:
      user_id: ユーザーUUID
      notify_citation: メッセージ引用通知
