version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.10.0
      - image: circleci/mysql:5.7.22-ram
        environment:
          - MYSQL_DATABASE=traq
          - MYSQL_ROOT_PASSWORD=password

    working_directory: /go/src/github.com/traPtitech/traQ

    steps:
      - checkout

      - run:
          name: Install tools/packages
          command: make init

      - run:
          name: fmt
          when: always
          command: make ci-fmt
      - run:
          name: vet
          when: always
          command: make ci-vet
      - run:
          name: lint
          when: always
          command: make ci-lint

      - run:
          name: Setup DB
          when: always
          command: |
            dockerize -wait tcp://localhost:3306 -timeout 1m
            go run .circleci/init.go

      - run:
          name: test
          when: always
          command: ./.circleci/go.test.sh
      - run:
          name: build
          when: always
          command: make traQ

      - run:
          name: Upload coverage data
          command: bash <(curl -s https://codecov.io/bash)

      - store_artifacts:
          path: /go/src/github.com/traPtitech/traQ/traQ
          destination: traQ
