// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: v4/admin.proto

package v4

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AdminService_GetVersion_FullMethodName            = "/v4.AdminService/GetVersion"
	AdminService_GetServerInfo_FullMethodName         = "/v4.AdminService/GetServerInfo"
	AdminService_GetClientConfig_FullMethodName       = "/v4.AdminService/GetClientConfig"
	AdminService_GetCacheConfig_FullMethodName        = "/v4.AdminService/GetCacheConfig"
	AdminService_GetUsers_FullMethodName              = "/v4.AdminService/GetUsers"
	AdminService_GetUser_FullMethodName               = "/v4.AdminService/GetUser"
	AdminService_SetUserAccountState_FullMethodName   = "/v4.AdminService/SetUserAccountState"
	AdminService_SetUserPassword_FullMethodName       = "/v4.AdminService/SetUserPassword"
	AdminService_EditUserRoles_FullMethodName         = "/v4.AdminService/EditUserRoles"
	AdminService_ChangeUserIconAdmin_FullMethodName   = "/v4.AdminService/ChangeUserIconAdmin"
	AdminService_EditUserTagAdmin_FullMethodName      = "/v4.AdminService/EditUserTagAdmin"
	AdminService_GetChannels_FullMethodName           = "/v4.AdminService/GetChannels"
	AdminService_GetChannel_FullMethodName            = "/v4.AdminService/GetChannel"
	AdminService_SetChannelTopic_FullMethodName       = "/v4.AdminService/SetChannelTopic"
	AdminService_GetUserGroupsAdmin_FullMethodName    = "/v4.AdminService/GetUserGroupsAdmin"
	AdminService_GetUserGroupAdmin_FullMethodName     = "/v4.AdminService/GetUserGroupAdmin"
	AdminService_AddUserGroupAdmin_FullMethodName     = "/v4.AdminService/AddUserGroupAdmin"
	AdminService_RemoveUserGroupAdmin_FullMethodName  = "/v4.AdminService/RemoveUserGroupAdmin"
	AdminService_GetClipFoldersAdmin_FullMethodName   = "/v4.AdminService/GetClipFoldersAdmin"
	AdminService_ChangeClipFolderOwner_FullMethodName = "/v4.AdminService/ChangeClipFolderOwner"
	AdminService_GetStampsAdmin_FullMethodName        = "/v4.AdminService/GetStampsAdmin"
	AdminService_ChangeStampCreator_FullMethodName    = "/v4.AdminService/ChangeStampCreator"
	AdminService_GetFilesAdmin_FullMethodName         = "/v4.AdminService/GetFilesAdmin"
	AdminService_ChangeFileChannel_FullMethodName     = "/v4.AdminService/ChangeFileChannel"
	AdminService_ImportMessages_FullMethodName        = "/v4.AdminService/ImportMessages"
	AdminService_GetServerConfigAdmin_FullMethodName  = "/v4.AdminService/GetServerConfigAdmin"
	AdminService_SetServerConfigAdmin_FullMethodName  = "/v4.AdminService/SetServerConfigAdmin"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	// サーバーのバージョン情報を取得します。
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*Version, error)
	// サーバーの情報を取得します。
	GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*ServerInfo, error)
	// クライアント設定を取得します。
	GetClientConfig(ctx context.Context, in *GetClientConfigRequest, opts ...grpc.CallOption) (*ClientConfig, error)
	// アセットのキャッシュ設定を取得します。
	GetCacheConfig(ctx context.Context, in *GetCacheConfigRequest, opts ...grpc.CallOption) (*CacheConfig, error)
	// 全てのユーザーのリストを取得します。
	GetUsers(ctx context.Context, in *GetUsersAdminRequest, opts ...grpc.CallOption) (*GetUsersAdminResponse, error)
	// 指定したユーザーの情報を取得します。
	GetUser(ctx context.Context, in *GetUserAdminRequest, opts ...grpc.CallOption) (*UserDetail, error)
	// ユーザーのアカウント状態を変更します。
	SetUserAccountState(ctx context.Context, in *SetUserAccountStateAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// ユーザーのパスワードを変更します。
	SetUserPassword(ctx context.Context, in *SetUserPasswordAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// ユーザーのロールを更新します。
	EditUserRoles(ctx context.Context, in *EditUserRolesAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// ユーザーのアイコンを変更します。
	ChangeUserIconAdmin(ctx context.Context, in *ChangeUserIconAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// ユーザーのタグを編集します。
	EditUserTagAdmin(ctx context.Context, in *EditUserTagAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// 全てのチャンネルのリストを取得します。
	GetChannels(ctx context.Context, in *GetChannelsAdminRequest, opts ...grpc.CallOption) (*GetChannelsAdminResponse, error)
	// 指定したチャンネルの情報を取得します。
	GetChannel(ctx context.Context, in *GetChannelAdminRequest, opts ...grpc.CallOption) (*Channel, error)
	// チャンネルのトピックを更新します。
	SetChannelTopic(ctx context.Context, in *SetChannelTopicAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// 全てのユーザーグループのリストを取得します。
	GetUserGroupsAdmin(ctx context.Context, in *GetUserGroupsAdminRequest, opts ...grpc.CallOption) (*GetUserGroupsAdminResponse, error)
	// 指定したユーザーグループの情報を取得します。
	GetUserGroupAdmin(ctx context.Context, in *GetUserGroupAdminRequest, opts ...grpc.CallOption) (*UserGroup, error)
	// ユーザーグループに管理者を追加します。
	AddUserGroupAdmin(ctx context.Context, in *AddUserGroupAdminAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// ユーザーグループの管理者から指定したユーザーを削除します。
	RemoveUserGroupAdmin(ctx context.Context, in *RemoveUserGroupAdminAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// 全てのクリップフォルダのリストを取得します。
	GetClipFoldersAdmin(ctx context.Context, in *GetClipFoldersAdminRequest, opts ...grpc.CallOption) (*GetClipFoldersAdminResponse, error)
	// クリップフォルダの所有者を変更します。
	ChangeClipFolderOwner(ctx context.Context, in *ChangeClipFolderOwnerAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// 全てのスタンプのリストを取得します。
	GetStampsAdmin(ctx context.Context, in *GetStampsAdminRequest, opts ...grpc.CallOption) (*GetStampsAdminResponse, error)
	// スタンプの作成者を変更します。
	ChangeStampCreator(ctx context.Context, in *ChangeStampCreatorAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// 全てのファイルのリストを取得します。
	GetFilesAdmin(ctx context.Context, in *GetFilesAdminRequest, opts ...grpc.CallOption) (*GetFilesAdminResponse, error)
	// ファイルのチャンネルIDを変更します。
	ChangeFileChannel(ctx context.Context, in *ChangeFileChannelAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// メッセージをインポートします。
	ImportMessages(ctx context.Context, in *ImportMessagesAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// サーバー設定を取得します。
	GetServerConfigAdmin(ctx context.Context, in *GetServerConfigAdminRequest, opts ...grpc.CallOption) (*AdminServerConfig, error)
	// サーバー設定を変更します。
	SetServerConfigAdmin(ctx context.Context, in *SetServerConfigAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*Version, error) {
	out := new(Version)
	err := c.cc.Invoke(ctx, AdminService_GetVersion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*ServerInfo, error) {
	out := new(ServerInfo)
	err := c.cc.Invoke(ctx, AdminService_GetServerInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetClientConfig(ctx context.Context, in *GetClientConfigRequest, opts ...grpc.CallOption) (*ClientConfig, error) {
	out := new(ClientConfig)
	err := c.cc.Invoke(ctx, AdminService_GetClientConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetCacheConfig(ctx context.Context, in *GetCacheConfigRequest, opts ...grpc.CallOption) (*CacheConfig, error) {
	out := new(CacheConfig)
	err := c.cc.Invoke(ctx, AdminService_GetCacheConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetUsers(ctx context.Context, in *GetUsersAdminRequest, opts ...grpc.CallOption) (*GetUsersAdminResponse, error) {
	out := new(GetUsersAdminResponse)
	err := c.cc.Invoke(ctx, AdminService_GetUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetUser(ctx context.Context, in *GetUserAdminRequest, opts ...grpc.CallOption) (*UserDetail, error) {
	out := new(UserDetail)
	err := c.cc.Invoke(ctx, AdminService_GetUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SetUserAccountState(ctx context.Context, in *SetUserAccountStateAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, AdminService_SetUserAccountState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SetUserPassword(ctx context.Context, in *SetUserPasswordAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, AdminService_SetUserPassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) EditUserRoles(ctx context.Context, in *EditUserRolesAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, AdminService_EditUserRoles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ChangeUserIconAdmin(ctx context.Context, in *ChangeUserIconAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, AdminService_ChangeUserIconAdmin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) EditUserTagAdmin(ctx context.Context, in *EditUserTagAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, AdminService_EditUserTagAdmin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetChannels(ctx context.Context, in *GetChannelsAdminRequest, opts ...grpc.CallOption) (*GetChannelsAdminResponse, error) {
	out := new(GetChannelsAdminResponse)
	err := c.cc.Invoke(ctx, AdminService_GetChannels_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetChannel(ctx context.Context, in *GetChannelAdminRequest, opts ...grpc.CallOption) (*Channel, error) {
	out := new(Channel)
	err := c.cc.Invoke(ctx, AdminService_GetChannel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SetChannelTopic(ctx context.Context, in *SetChannelTopicAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, AdminService_SetChannelTopic_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetUserGroupsAdmin(ctx context.Context, in *GetUserGroupsAdminRequest, opts ...grpc.CallOption) (*GetUserGroupsAdminResponse, error) {
	out := new(GetUserGroupsAdminResponse)
	err := c.cc.Invoke(ctx, AdminService_GetUserGroupsAdmin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetUserGroupAdmin(ctx context.Context, in *GetUserGroupAdminRequest, opts ...grpc.CallOption) (*UserGroup, error) {
	out := new(UserGroup)
	err := c.cc.Invoke(ctx, AdminService_GetUserGroupAdmin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AddUserGroupAdmin(ctx context.Context, in *AddUserGroupAdminAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, AdminService_AddUserGroupAdmin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RemoveUserGroupAdmin(ctx context.Context, in *RemoveUserGroupAdminAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, AdminService_RemoveUserGroupAdmin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetClipFoldersAdmin(ctx context.Context, in *GetClipFoldersAdminRequest, opts ...grpc.CallOption) (*GetClipFoldersAdminResponse, error) {
	out := new(GetClipFoldersAdminResponse)
	err := c.cc.Invoke(ctx, AdminService_GetClipFoldersAdmin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ChangeClipFolderOwner(ctx context.Context, in *ChangeClipFolderOwnerAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, AdminService_ChangeClipFolderOwner_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetStampsAdmin(ctx context.Context, in *GetStampsAdminRequest, opts ...grpc.CallOption) (*GetStampsAdminResponse, error) {
	out := new(GetStampsAdminResponse)
	err := c.cc.Invoke(ctx, AdminService_GetStampsAdmin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ChangeStampCreator(ctx context.Context, in *ChangeStampCreatorAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, AdminService_ChangeStampCreator_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetFilesAdmin(ctx context.Context, in *GetFilesAdminRequest, opts ...grpc.CallOption) (*GetFilesAdminResponse, error) {
	out := new(GetFilesAdminResponse)
	err := c.cc.Invoke(ctx, AdminService_GetFilesAdmin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ChangeFileChannel(ctx context.Context, in *ChangeFileChannelAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, AdminService_ChangeFileChannel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ImportMessages(ctx context.Context, in *ImportMessagesAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, AdminService_ImportMessages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetServerConfigAdmin(ctx context.Context, in *GetServerConfigAdminRequest, opts ...grpc.CallOption) (*AdminServerConfig, error) {
	out := new(AdminServerConfig)
	err := c.cc.Invoke(ctx, AdminService_GetServerConfigAdmin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SetServerConfigAdmin(ctx context.Context, in *SetServerConfigAdminRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, AdminService_SetServerConfigAdmin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility
type AdminServiceServer interface {
	// サーバーのバージョン情報を取得します。
	GetVersion(context.Context, *GetVersionRequest) (*Version, error)
	// サーバーの情報を取得します。
	GetServerInfo(context.Context, *GetServerInfoRequest) (*ServerInfo, error)
	// クライアント設定を取得します。
	GetClientConfig(context.Context, *GetClientConfigRequest) (*ClientConfig, error)
	// アセットのキャッシュ設定を取得します。
	GetCacheConfig(context.Context, *GetCacheConfigRequest) (*CacheConfig, error)
	// 全てのユーザーのリストを取得します。
	GetUsers(context.Context, *GetUsersAdminRequest) (*GetUsersAdminResponse, error)
	// 指定したユーザーの情報を取得します。
	GetUser(context.Context, *GetUserAdminRequest) (*UserDetail, error)
	// ユーザーのアカウント状態を変更します。
	SetUserAccountState(context.Context, *SetUserAccountStateAdminRequest) (*EmptyResponse, error)
	// ユーザーのパスワードを変更します。
	SetUserPassword(context.Context, *SetUserPasswordAdminRequest) (*EmptyResponse, error)
	// ユーザーのロールを更新します。
	EditUserRoles(context.Context, *EditUserRolesAdminRequest) (*EmptyResponse, error)
	// ユーザーのアイコンを変更します。
	ChangeUserIconAdmin(context.Context, *ChangeUserIconAdminRequest) (*EmptyResponse, error)
	// ユーザーのタグを編集します。
	EditUserTagAdmin(context.Context, *EditUserTagAdminRequest) (*EmptyResponse, error)
	// 全てのチャンネルのリストを取得します。
	GetChannels(context.Context, *GetChannelsAdminRequest) (*GetChannelsAdminResponse, error)
	// 指定したチャンネルの情報を取得します。
	GetChannel(context.Context, *GetChannelAdminRequest) (*Channel, error)
	// チャンネルのトピックを更新します。
	SetChannelTopic(context.Context, *SetChannelTopicAdminRequest) (*EmptyResponse, error)
	// 全てのユーザーグループのリストを取得します。
	GetUserGroupsAdmin(context.Context, *GetUserGroupsAdminRequest) (*GetUserGroupsAdminResponse, error)
	// 指定したユーザーグループの情報を取得します。
	GetUserGroupAdmin(context.Context, *GetUserGroupAdminRequest) (*UserGroup, error)
	// ユーザーグループに管理者を追加します。
	AddUserGroupAdmin(context.Context, *AddUserGroupAdminAdminRequest) (*EmptyResponse, error)
	// ユーザーグループの管理者から指定したユーザーを削除します。
	RemoveUserGroupAdmin(context.Context, *RemoveUserGroupAdminAdminRequest) (*EmptyResponse, error)
	// 全てのクリップフォルダのリストを取得します。
	GetClipFoldersAdmin(context.Context, *GetClipFoldersAdminRequest) (*GetClipFoldersAdminResponse, error)
	// クリップフォルダの所有者を変更します。
	ChangeClipFolderOwner(context.Context, *ChangeClipFolderOwnerAdminRequest) (*EmptyResponse, error)
	// 全てのスタンプのリストを取得します。
	GetStampsAdmin(context.Context, *GetStampsAdminRequest) (*GetStampsAdminResponse, error)
	// スタンプの作成者を変更します。
	ChangeStampCreator(context.Context, *ChangeStampCreatorAdminRequest) (*EmptyResponse, error)
	// 全てのファイルのリストを取得します。
	GetFilesAdmin(context.Context, *GetFilesAdminRequest) (*GetFilesAdminResponse, error)
	// ファイルのチャンネルIDを変更します。
	ChangeFileChannel(context.Context, *ChangeFileChannelAdminRequest) (*EmptyResponse, error)
	// メッセージをインポートします。
	ImportMessages(context.Context, *ImportMessagesAdminRequest) (*EmptyResponse, error)
	// サーバー設定を取得します。
	GetServerConfigAdmin(context.Context, *GetServerConfigAdminRequest) (*AdminServerConfig, error)
	// サーバー設定を変更します。
	SetServerConfigAdmin(context.Context, *SetServerConfigAdminRequest) (*EmptyResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServiceServer struct {
}

func (UnimplementedAdminServiceServer) GetVersion(context.Context, *GetVersionRequest) (*Version, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedAdminServiceServer) GetServerInfo(context.Context, *GetServerInfoRequest) (*ServerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerInfo not implemented")
}
func (UnimplementedAdminServiceServer) GetClientConfig(context.Context, *GetClientConfigRequest) (*ClientConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientConfig not implemented")
}
func (UnimplementedAdminServiceServer) GetCacheConfig(context.Context, *GetCacheConfigRequest) (*CacheConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCacheConfig not implemented")
}
func (UnimplementedAdminServiceServer) GetUsers(context.Context, *GetUsersAdminRequest) (*GetUsersAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedAdminServiceServer) GetUser(context.Context, *GetUserAdminRequest) (*UserDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedAdminServiceServer) SetUserAccountState(context.Context, *SetUserAccountStateAdminRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserAccountState not implemented")
}
func (UnimplementedAdminServiceServer) SetUserPassword(context.Context, *SetUserPasswordAdminRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserPassword not implemented")
}
func (UnimplementedAdminServiceServer) EditUserRoles(context.Context, *EditUserRolesAdminRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditUserRoles not implemented")
}
func (UnimplementedAdminServiceServer) ChangeUserIconAdmin(context.Context, *ChangeUserIconAdminRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeUserIconAdmin not implemented")
}
func (UnimplementedAdminServiceServer) EditUserTagAdmin(context.Context, *EditUserTagAdminRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditUserTagAdmin not implemented")
}
func (UnimplementedAdminServiceServer) GetChannels(context.Context, *GetChannelsAdminRequest) (*GetChannelsAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChannels not implemented")
}
func (UnimplementedAdminServiceServer) GetChannel(context.Context, *GetChannelAdminRequest) (*Channel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChannel not implemented")
}
func (UnimplementedAdminServiceServer) SetChannelTopic(context.Context, *SetChannelTopicAdminRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetChannelTopic not implemented")
}
func (UnimplementedAdminServiceServer) GetUserGroupsAdmin(context.Context, *GetUserGroupsAdminRequest) (*GetUserGroupsAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserGroupsAdmin not implemented")
}
func (UnimplementedAdminServiceServer) GetUserGroupAdmin(context.Context, *GetUserGroupAdminRequest) (*UserGroup, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserGroupAdmin not implemented")
}
func (UnimplementedAdminServiceServer) AddUserGroupAdmin(context.Context, *AddUserGroupAdminAdminRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserGroupAdmin not implemented")
}
func (UnimplementedAdminServiceServer) RemoveUserGroupAdmin(context.Context, *RemoveUserGroupAdminAdminRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUserGroupAdmin not implemented")
}
func (UnimplementedAdminServiceServer) GetClipFoldersAdmin(context.Context, *GetClipFoldersAdminRequest) (*GetClipFoldersAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClipFoldersAdmin not implemented")
}
func (UnimplementedAdminServiceServer) ChangeClipFolderOwner(context.Context, *ChangeClipFolderOwnerAdminRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeClipFolderOwner not implemented")
}
func (UnimplementedAdminServiceServer) GetStampsAdmin(context.Context, *GetStampsAdminRequest) (*GetStampsAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStampsAdmin not implemented")
}
func (UnimplementedAdminServiceServer) ChangeStampCreator(context.Context, *ChangeStampCreatorAdminRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeStampCreator not implemented")
}
func (UnimplementedAdminServiceServer) GetFilesAdmin(context.Context, *GetFilesAdminRequest) (*GetFilesAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFilesAdmin not implemented")
}
func (UnimplementedAdminServiceServer) ChangeFileChannel(context.Context, *ChangeFileChannelAdminRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeFileChannel not implemented")
}
func (UnimplementedAdminServiceServer) ImportMessages(context.Context, *ImportMessagesAdminRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportMessages not implemented")
}
func (UnimplementedAdminServiceServer) GetServerConfigAdmin(context.Context, *GetServerConfigAdminRequest) (*AdminServerConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerConfigAdmin not implemented")
}
func (UnimplementedAdminServiceServer) SetServerConfigAdmin(context.Context, *SetServerConfigAdminRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetServerConfigAdmin not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetServerInfo(ctx, req.(*GetServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetClientConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetClientConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetClientConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetClientConfig(ctx, req.(*GetClientConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetCacheConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCacheConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetCacheConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetCacheConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetCacheConfig(ctx, req.(*GetCacheConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetUsers(ctx, req.(*GetUsersAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetUser(ctx, req.(*GetUserAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SetUserAccountState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserAccountStateAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetUserAccountState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SetUserAccountState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetUserAccountState(ctx, req.(*SetUserAccountStateAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SetUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserPasswordAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SetUserPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetUserPassword(ctx, req.(*SetUserPasswordAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_EditUserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditUserRolesAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).EditUserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_EditUserRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).EditUserRoles(ctx, req.(*EditUserRolesAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ChangeUserIconAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeUserIconAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ChangeUserIconAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ChangeUserIconAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ChangeUserIconAdmin(ctx, req.(*ChangeUserIconAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_EditUserTagAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditUserTagAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).EditUserTagAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_EditUserTagAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).EditUserTagAdmin(ctx, req.(*EditUserTagAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelsAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetChannels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetChannels(ctx, req.(*GetChannelsAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetChannel(ctx, req.(*GetChannelAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SetChannelTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetChannelTopicAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetChannelTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SetChannelTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetChannelTopic(ctx, req.(*SetChannelTopicAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetUserGroupsAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserGroupsAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetUserGroupsAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetUserGroupsAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetUserGroupsAdmin(ctx, req.(*GetUserGroupsAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetUserGroupAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserGroupAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetUserGroupAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetUserGroupAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetUserGroupAdmin(ctx, req.(*GetUserGroupAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AddUserGroupAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserGroupAdminAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AddUserGroupAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_AddUserGroupAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AddUserGroupAdmin(ctx, req.(*AddUserGroupAdminAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RemoveUserGroupAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserGroupAdminAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RemoveUserGroupAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RemoveUserGroupAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RemoveUserGroupAdmin(ctx, req.(*RemoveUserGroupAdminAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetClipFoldersAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClipFoldersAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetClipFoldersAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetClipFoldersAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetClipFoldersAdmin(ctx, req.(*GetClipFoldersAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ChangeClipFolderOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeClipFolderOwnerAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ChangeClipFolderOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ChangeClipFolderOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ChangeClipFolderOwner(ctx, req.(*ChangeClipFolderOwnerAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetStampsAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStampsAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetStampsAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetStampsAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetStampsAdmin(ctx, req.(*GetStampsAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ChangeStampCreator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeStampCreatorAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ChangeStampCreator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ChangeStampCreator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ChangeStampCreator(ctx, req.(*ChangeStampCreatorAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetFilesAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilesAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetFilesAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetFilesAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetFilesAdmin(ctx, req.(*GetFilesAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ChangeFileChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeFileChannelAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ChangeFileChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ChangeFileChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ChangeFileChannel(ctx, req.(*ChangeFileChannelAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ImportMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportMessagesAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ImportMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ImportMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ImportMessages(ctx, req.(*ImportMessagesAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetServerConfigAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerConfigAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetServerConfigAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetServerConfigAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetServerConfigAdmin(ctx, req.(*GetServerConfigAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SetServerConfigAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetServerConfigAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetServerConfigAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SetServerConfigAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetServerConfigAdmin(ctx, req.(*SetServerConfigAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v4.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _AdminService_GetVersion_Handler,
		},
		{
			MethodName: "GetServerInfo",
			Handler:    _AdminService_GetServerInfo_Handler,
		},
		{
			MethodName: "GetClientConfig",
			Handler:    _AdminService_GetClientConfig_Handler,
		},
		{
			MethodName: "GetCacheConfig",
			Handler:    _AdminService_GetCacheConfig_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _AdminService_GetUsers_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AdminService_GetUser_Handler,
		},
		{
			MethodName: "SetUserAccountState",
			Handler:    _AdminService_SetUserAccountState_Handler,
		},
		{
			MethodName: "SetUserPassword",
			Handler:    _AdminService_SetUserPassword_Handler,
		},
		{
			MethodName: "EditUserRoles",
			Handler:    _AdminService_EditUserRoles_Handler,
		},
		{
			MethodName: "ChangeUserIconAdmin",
			Handler:    _AdminService_ChangeUserIconAdmin_Handler,
		},
		{
			MethodName: "EditUserTagAdmin",
			Handler:    _AdminService_EditUserTagAdmin_Handler,
		},
		{
			MethodName: "GetChannels",
			Handler:    _AdminService_GetChannels_Handler,
		},
		{
			MethodName: "GetChannel",
			Handler:    _AdminService_GetChannel_Handler,
		},
		{
			MethodName: "SetChannelTopic",
			Handler:    _AdminService_SetChannelTopic_Handler,
		},
		{
			MethodName: "GetUserGroupsAdmin",
			Handler:    _AdminService_GetUserGroupsAdmin_Handler,
		},
		{
			MethodName: "GetUserGroupAdmin",
			Handler:    _AdminService_GetUserGroupAdmin_Handler,
		},
		{
			MethodName: "AddUserGroupAdmin",
			Handler:    _AdminService_AddUserGroupAdmin_Handler,
		},
		{
			MethodName: "RemoveUserGroupAdmin",
			Handler:    _AdminService_RemoveUserGroupAdmin_Handler,
		},
		{
			MethodName: "GetClipFoldersAdmin",
			Handler:    _AdminService_GetClipFoldersAdmin_Handler,
		},
		{
			MethodName: "ChangeClipFolderOwner",
			Handler:    _AdminService_ChangeClipFolderOwner_Handler,
		},
		{
			MethodName: "GetStampsAdmin",
			Handler:    _AdminService_GetStampsAdmin_Handler,
		},
		{
			MethodName: "ChangeStampCreator",
			Handler:    _AdminService_ChangeStampCreator_Handler,
		},
		{
			MethodName: "GetFilesAdmin",
			Handler:    _AdminService_GetFilesAdmin_Handler,
		},
		{
			MethodName: "ChangeFileChannel",
			Handler:    _AdminService_ChangeFileChannel_Handler,
		},
		{
			MethodName: "ImportMessages",
			Handler:    _AdminService_ImportMessages_Handler,
		},
		{
			MethodName: "GetServerConfigAdmin",
			Handler:    _AdminService_GetServerConfigAdmin_Handler,
		},
		{
			MethodName: "SetServerConfigAdmin",
			Handler:    _AdminService_SetServerConfigAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v4/admin.proto",
}
