// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: v4/bot.proto

package v4

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BOT情報
type Bot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// BOT UUID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// BOTユーザーUUID
	BotUserId string `protobuf:"bytes,2,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	// BOTの説明
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// BOT開発者UUID
	DeveloperId string `protobuf:"bytes,4,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	// BOTが購読しているイベントの配列
	SubscribeEvents []string `protobuf:"bytes,5,rep,name=subscribe_events,json=subscribeEvents,proto3" json:"subscribe_events,omitempty"`
	// BOTモード
	Mode BotMode `protobuf:"varint,6,opt,name=mode,proto3,enum=v4.BotMode" json:"mode,omitempty"` // Removed common.
	// BOTが作成された日時
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// BOTが更新された日時
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// BOT状態
	State UserAccountState `protobuf:"varint,9,opt,name=state,proto3,enum=v4.UserAccountState" json:"state,omitempty"` // Removed common.
}

func (x *Bot) Reset() {
	*x = Bot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bot) ProtoMessage() {}

func (x *Bot) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bot.ProtoReflect.Descriptor instead.
func (*Bot) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{0}
}

func (x *Bot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bot) GetBotUserId() string {
	if x != nil {
		return x.BotUserId
	}
	return ""
}

func (x *Bot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Bot) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

func (x *Bot) GetSubscribeEvents() []string {
	if x != nil {
		return x.SubscribeEvents
	}
	return nil
}

func (x *Bot) GetMode() BotMode {
	if x != nil {
		return x.Mode
	}
	return BotMode_BOT_MODE_UNSPECIFIED
}

func (x *Bot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Bot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Bot) GetState() UserAccountState {
	if x != nil {
		return x.State
	}
	return UserAccountState_USER_ACCOUNT_STATE_UNSPECIFIED
}

// BOT詳細情報
type BotDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// BOT UUID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// BOTユーザーUUID
	BotUserId string `protobuf:"bytes,2,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	// BOTの説明
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// BOT開発者UUID
	DeveloperId string `protobuf:"bytes,4,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	// BOTが購読しているイベントの配列
	SubscribeEvents []string `protobuf:"bytes,5,rep,name=subscribe_events,json=subscribeEvents,proto3" json:"subscribe_events,omitempty"`
	// BOTモード
	Mode BotMode `protobuf:"varint,7,opt,name=mode,proto3,enum=v4.BotMode" json:"mode,omitempty"` // Removed common.
	// 特権BOTかどうか
	Privileged bool `protobuf:"varint,8,opt,name=privileged,proto3" json:"privileged,omitempty"`
	// BOTサーバーエンドポイント
	Endpoint string `protobuf:"bytes,9,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// 作成日時
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 更新日時
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// BOT状態
	State UserAccountState `protobuf:"varint,12,opt,name=state,proto3,enum=v4.UserAccountState" json:"state,omitempty"` // Removed common.
	// BOTが参加しているチャンネルのUUID配列
	ChannelIds []string `protobuf:"bytes,13,rep,name=channel_ids,json=channelIds,proto3" json:"channel_ids,omitempty"`
	// BOTのアイコンファイルUUID
	IconFileId string `protobuf:"bytes,14,opt,name=icon_file_id,json=iconFileId,proto3" json:"icon_file_id,omitempty"`
	// BOTの現在のセッションのWebhook Sigmund ID
	CurrentWebhookId string `protobuf:"bytes,15,opt,name=current_webhook_id,json=currentWebhookId,proto3" json:"current_webhook_id,omitempty"`
}

func (x *BotDetail) Reset() {
	*x = BotDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotDetail) ProtoMessage() {}

func (x *BotDetail) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotDetail.ProtoReflect.Descriptor instead.
func (*BotDetail) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{1}
}

func (x *BotDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BotDetail) GetBotUserId() string {
	if x != nil {
		return x.BotUserId
	}
	return ""
}

func (x *BotDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BotDetail) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

func (x *BotDetail) GetSubscribeEvents() []string {
	if x != nil {
		return x.SubscribeEvents
	}
	return nil
}

func (x *BotDetail) GetMode() BotMode {
	if x != nil {
		return x.Mode
	}
	return BotMode_BOT_MODE_UNSPECIFIED
}

func (x *BotDetail) GetPrivileged() bool {
	if x != nil {
		return x.Privileged
	}
	return false
}

func (x *BotDetail) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *BotDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BotDetail) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BotDetail) GetState() UserAccountState {
	if x != nil {
		return x.State
	}
	return UserAccountState_USER_ACCOUNT_STATE_UNSPECIFIED
}

func (x *BotDetail) GetChannelIds() []string {
	if x != nil {
		return x.ChannelIds
	}
	return nil
}

func (x *BotDetail) GetIconFileId() string {
	if x != nil {
		return x.IconFileId
	}
	return ""
}

func (x *BotDetail) GetCurrentWebhookId() string {
	if x != nil {
		return x.CurrentWebhookId
	}
	return ""
}

// BOT作成リクエスト
type PostBotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// BOT名
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// BOT表示名
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// BOTの説明
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// BOTモード
	Mode BotMode `protobuf:"varint,4,opt,name=mode,proto3,enum=v4.BotMode" json:"mode,omitempty"` // Removed common.
	// BOTサーバーエンドポイント
	Endpoint string `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
}

func (x *PostBotRequest) Reset() {
	*x = PostBotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBotRequest) ProtoMessage() {}

func (x *PostBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBotRequest.ProtoReflect.Descriptor instead.
func (*PostBotRequest) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{2}
}

func (x *PostBotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PostBotRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PostBotRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PostBotRequest) GetMode() BotMode {
	if x != nil {
		return x.Mode
	}
	return BotMode_BOT_MODE_UNSPECIFIED
}

func (x *PostBotRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

// BOT情報編集リクエスト
type PatchBotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// BOT表示名
	DisplayName *string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	// BOTの説明
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// 特権BOTかどうか
	Privileged *bool `protobuf:"varint,3,opt,name=privileged,proto3,oneof" json:"privileged,omitempty"`
	// BOTモード
	Mode *BotMode `protobuf:"varint,4,opt,name=mode,proto3,enum=v4.BotMode,oneof" json:"mode,omitempty"` // Removed common.
	// BOTサーバーエンドポイント
	Endpoint *string `protobuf:"bytes,5,opt,name=endpoint,proto3,oneof" json:"endpoint,omitempty"`
	// BOT開発者UUID
	DeveloperId *string `protobuf:"bytes,6,opt,name=developer_id,json=developerId,proto3,oneof" json:"developer_id,omitempty"`
	// BOTが購読するイベントの配列
	SubscribeEvents []string `protobuf:"bytes,7,rep,name=subscribe_events,json=subscribeEvents,proto3" json:"subscribe_events,omitempty"`
}

func (x *PatchBotRequest) Reset() {
	*x = PatchBotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchBotRequest) ProtoMessage() {}

func (x *PatchBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchBotRequest.ProtoReflect.Descriptor instead.
func (*PatchBotRequest) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{3}
}

func (x *PatchBotRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *PatchBotRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *PatchBotRequest) GetPrivileged() bool {
	if x != nil && x.Privileged != nil {
		return *x.Privileged
	}
	return false
}

func (x *PatchBotRequest) GetMode() BotMode {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return BotMode_BOT_MODE_UNSPECIFIED
}

func (x *PatchBotRequest) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

func (x *PatchBotRequest) GetDeveloperId() string {
	if x != nil && x.DeveloperId != nil {
		return *x.DeveloperId
	}
	return ""
}

func (x *PatchBotRequest) GetSubscribeEvents() []string {
	if x != nil {
		return x.SubscribeEvents
	}
	return nil
}

// BOTイベントログ
type BotEventLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// BOT UUID
	BotId string `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	// リクエストUUID
	RequestId string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// イベントタイプ
	Event BotEvent `protobuf:"varint,3,opt,name=event,proto3,enum=v4.BotEvent" json:"event,omitempty"` // Removed common.
	// ステータスコード
	StatusCode int32 `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// イベント日時
	Datetime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=datetime,proto3" json:"datetime,omitempty"`
}

func (x *BotEventLog) Reset() {
	*x = BotEventLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotEventLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotEventLog) ProtoMessage() {}

func (x *BotEventLog) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotEventLog.ProtoReflect.Descriptor instead.
func (*BotEventLog) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{4}
}

func (x *BotEventLog) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *BotEventLog) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BotEventLog) GetEvent() BotEvent {
	if x != nil {
		return x.Event
	}
	return BotEvent_BOT_EVENT_UNSPECIFIED
}

func (x *BotEventLog) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BotEventLog) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

// BOT参加チャンネル情報
type BotJoinChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// チャンネルUUID
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (x *BotJoinChannel) Reset() {
	*x = BotJoinChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotJoinChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotJoinChannel) ProtoMessage() {}

func (x *BotJoinChannel) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotJoinChannel.ProtoReflect.Descriptor instead.
func (*BotJoinChannel) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{5}
}

func (x *BotJoinChannel) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

// BOT退出チャンネル情報
type BotLeaveChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// チャンネルUUID
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (x *BotLeaveChannel) Reset() {
	*x = BotLeaveChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotLeaveChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotLeaveChannel) ProtoMessage() {}

func (x *BotLeaveChannel) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotLeaveChannel.ProtoReflect.Descriptor instead.
func (*BotLeaveChannel) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{6}
}

func (x *BotLeaveChannel) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

// BOTのトークン再発行リクエスト
type ReissueBotTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReissueBotTokenRequest) Reset() {
	*x = ReissueBotTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReissueBotTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReissueBotTokenRequest) ProtoMessage() {}

func (x *ReissueBotTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReissueBotTokenRequest.ProtoReflect.Descriptor instead.
func (*ReissueBotTokenRequest) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{7}
}

// BOTのトークン情報
type BotTokens struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Verification Token
	VerificationToken string `protobuf:"bytes,1,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	// BOTアクセストークン
	AccessToken string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
}

func (x *BotTokens) Reset() {
	*x = BotTokens{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotTokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotTokens) ProtoMessage() {}

func (x *BotTokens) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotTokens.ProtoReflect.Descriptor instead.
func (*BotTokens) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{8}
}

func (x *BotTokens) GetVerificationToken() string {
	if x != nil {
		return x.VerificationToken
	}
	return ""
}

func (x *BotTokens) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type GetBotsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 全てのBOTを取得するかどうか
	All *bool `protobuf:"varint,1,opt,name=all,proto3,oneof" json:"all,omitempty"`
}

func (x *GetBotsRequest) Reset() {
	*x = GetBotsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotsRequest) ProtoMessage() {}

func (x *GetBotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotsRequest.ProtoReflect.Descriptor instead.
func (*GetBotsRequest) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{9}
}

func (x *GetBotsRequest) GetAll() bool {
	if x != nil && x.All != nil {
		return *x.All
	}
	return false
}

type GetBotsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bots []*Bot `protobuf:"bytes,1,rep,name=bots,proto3" json:"bots,omitempty"`
}

func (x *GetBotsResponse) Reset() {
	*x = GetBotsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotsResponse) ProtoMessage() {}

func (x *GetBotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotsResponse.ProtoReflect.Descriptor instead.
func (*GetBotsResponse) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{10}
}

func (x *GetBotsResponse) GetBots() []*Bot {
	if x != nil {
		return x.Bots
	}
	return nil
}

type GetBotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotId string `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	// 詳細情報を取得するかどうか
	Detail *bool `protobuf:"varint,2,opt,name=detail,proto3,oneof" json:"detail,omitempty"`
}

func (x *GetBotRequest) Reset() {
	*x = GetBotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotRequest) ProtoMessage() {}

func (x *GetBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotRequest.ProtoReflect.Descriptor instead.
func (*GetBotRequest) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{11}
}

func (x *GetBotRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *GetBotRequest) GetDetail() bool {
	if x != nil && x.Detail != nil {
		return *x.Detail
	}
	return false
}

type EditBotRpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotId   string           `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Payload *PatchBotRequest `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *EditBotRpcRequest) Reset() {
	*x = EditBotRpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditBotRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditBotRpcRequest) ProtoMessage() {}

func (x *EditBotRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditBotRpcRequest.ProtoReflect.Descriptor instead.
func (*EditBotRpcRequest) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{12}
}

func (x *EditBotRpcRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *EditBotRpcRequest) GetPayload() *PatchBotRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DeleteBotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotId string `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
}

func (x *DeleteBotRequest) Reset() {
	*x = DeleteBotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBotRequest) ProtoMessage() {}

func (x *DeleteBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBotRequest.ProtoReflect.Descriptor instead.
func (*DeleteBotRequest) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteBotRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type ActivateBotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotId string `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
}

func (x *ActivateBotRequest) Reset() {
	*x = ActivateBotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivateBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateBotRequest) ProtoMessage() {}

func (x *ActivateBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateBotRequest.ProtoReflect.Descriptor instead.
func (*ActivateBotRequest) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{14}
}

func (x *ActivateBotRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type InactivateBotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotId string `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
}

func (x *InactivateBotRequest) Reset() {
	*x = InactivateBotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InactivateBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InactivateBotRequest) ProtoMessage() {}

func (x *InactivateBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InactivateBotRequest.ProtoReflect.Descriptor instead.
func (*InactivateBotRequest) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{15}
}

func (x *InactivateBotRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type GetBotChannelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotId string `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
}

func (x *GetBotChannelsRequest) Reset() {
	*x = GetBotChannelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBotChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotChannelsRequest) ProtoMessage() {}

func (x *GetBotChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotChannelsRequest.ProtoReflect.Descriptor instead.
func (*GetBotChannelsRequest) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{16}
}

func (x *GetBotChannelsRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type GetBotChannelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channels []*BotJoinChannel `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"` // OpenAPIでは`ids`だが、ここでは構造体を使用
}

func (x *GetBotChannelsResponse) Reset() {
	*x = GetBotChannelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBotChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotChannelsResponse) ProtoMessage() {}

func (x *GetBotChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotChannelsResponse.ProtoReflect.Descriptor instead.
func (*GetBotChannelsResponse) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{17}
}

func (x *GetBotChannelsResponse) GetChannels() []*BotJoinChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type LetBotJoinChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotId string `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	// チャンネルUUID
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // OpenAPIではPostBotActionJoinRequestだが、ここでは直接指定
}

func (x *LetBotJoinChannelRequest) Reset() {
	*x = LetBotJoinChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LetBotJoinChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LetBotJoinChannelRequest) ProtoMessage() {}

func (x *LetBotJoinChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LetBotJoinChannelRequest.ProtoReflect.Descriptor instead.
func (*LetBotJoinChannelRequest) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{18}
}

func (x *LetBotJoinChannelRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *LetBotJoinChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type LetBotLeaveChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotId string `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	// チャンネルUUID
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // OpenAPIではPostBotActionLeaveRequestだが、ここでは直接指定
}

func (x *LetBotLeaveChannelRequest) Reset() {
	*x = LetBotLeaveChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LetBotLeaveChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LetBotLeaveChannelRequest) ProtoMessage() {}

func (x *LetBotLeaveChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LetBotLeaveChannelRequest.ProtoReflect.Descriptor instead.
func (*LetBotLeaveChannelRequest) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{19}
}

func (x *LetBotLeaveChannelRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *LetBotLeaveChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type ChangeBotIconRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotId string `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	// アイコン画像ファイルUUID
	FileId string `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
}

func (x *ChangeBotIconRequest) Reset() {
	*x = ChangeBotIconRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeBotIconRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeBotIconRequest) ProtoMessage() {}

func (x *ChangeBotIconRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeBotIconRequest.ProtoReflect.Descriptor instead.
func (*ChangeBotIconRequest) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{20}
}

func (x *ChangeBotIconRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *ChangeBotIconRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetBotLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotId string `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	// 取得する件数
	Limit *int32 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// 取得するオフセット
	Offset *int32 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
}

func (x *GetBotLogsRequest) Reset() {
	*x = GetBotLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBotLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotLogsRequest) ProtoMessage() {}

func (x *GetBotLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotLogsRequest.ProtoReflect.Descriptor instead.
func (*GetBotLogsRequest) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{21}
}

func (x *GetBotLogsRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *GetBotLogsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetBotLogsRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type GetBotLogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logs []*BotEventLog `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
}

func (x *GetBotLogsResponse) Reset() {
	*x = GetBotLogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBotLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotLogsResponse) ProtoMessage() {}

func (x *GetBotLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotLogsResponse.ProtoReflect.Descriptor instead.
func (*GetBotLogsResponse) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{22}
}

func (x *GetBotLogsResponse) GetLogs() []*BotEventLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type ReissueBotRpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotId string `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"` // ReissueBotTokenRequest payload = 2; // No payload in OpenAPI
}

func (x *ReissueBotRpcRequest) Reset() {
	*x = ReissueBotRpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReissueBotRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReissueBotRpcRequest) ProtoMessage() {}

func (x *ReissueBotRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReissueBotRpcRequest.ProtoReflect.Descriptor instead.
func (*ReissueBotRpcRequest) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{23}
}

func (x *ReissueBotRpcRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type GetBotIconRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotId string `protobuf:"bytes,1,opt,name=botId,proto3" json:"botId,omitempty"`
}

func (x *GetBotIconRequest) Reset() {
	*x = GetBotIconRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_bot_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBotIconRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotIconRequest) ProtoMessage() {}

func (x *GetBotIconRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_bot_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotIconRequest.ProtoReflect.Descriptor instead.
func (*GetBotIconRequest) Descriptor() ([]byte, []int) {
	return file_v4_bot_proto_rawDescGZIP(), []int{24}
}

func (x *GetBotIconRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

var File_v4_bot_proto protoreflect.FileDescriptor

var file_v4_bot_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x76, 0x34, 0x2f, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x76, 0x34, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x76, 0x34, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe8, 0x02, 0x0a, 0x03, 0x42, 0x6f, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0b,
	0x62, 0x6f, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x62, 0x6f, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21,
	0x0a, 0x0c, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x5f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x04,
	0x6d, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x76, 0x34, 0x2e,
	0x42, 0x6f, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x39, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x76, 0x34, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22,
	0x9b, 0x04, 0x0a, 0x09, 0x42, 0x6f, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a,
	0x0b, 0x62, 0x6f, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x21, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x5f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1f, 0x0a,
	0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x76, 0x34,
	0x2e, 0x42, 0x6f, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x2a, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x14, 0x2e, 0x76, 0x34, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x73, 0x12, 0x20, 0x0a,
	0x0c, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x63, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x2c, 0x0a, 0x12, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x77, 0x65, 0x62, 0x68, 0x6f,
	0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x22, 0xa6, 0x01,
	0x0a, 0x0e, 0x50, 0x6f, 0x73, 0x74, 0x42, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x76, 0x34, 0x2e, 0x42, 0x6f, 0x74,
	0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0xf6, 0x02, 0x0a, 0x0f, 0x50, 0x61, 0x74, 0x63, 0x68,
	0x42, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0c, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0a, 0x70, 0x72, 0x69,
	0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x02, 0x52,
	0x0a, 0x70, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x64, 0x88, 0x01, 0x01, 0x12, 0x24,
	0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x76,
	0x34, 0x2e, 0x42, 0x6f, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x48, 0x03, 0x52, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x04, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x05, 0x52, 0x0b, 0x64,
	0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x29, 0x0a,
	0x10, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x64, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x70, 0x72,
	0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6d, 0x6f, 0x64,
	0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x42, 0x0f,
	0x0a, 0x0d, 0x5f, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x22,
	0xc0, 0x01, 0x0a, 0x0b, 0x42, 0x6f, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x12,
	0x15, 0x0a, 0x06, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x76, 0x34, 0x2e, 0x42, 0x6f, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x64, 0x61,
	0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69,
	0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x0e, 0x42, 0x6f, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x0f, 0x42, 0x6f, 0x74, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x52, 0x65, 0x69, 0x73, 0x73, 0x75, 0x65,
	0x42, 0x6f, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x5d, 0x0a, 0x09, 0x42, 0x6f, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x12,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2f,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x15, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52,
	0x03, 0x61, 0x6c, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x61, 0x6c, 0x6c, 0x22,
	0x2e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x62, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x07, 0x2e, 0x76, 0x34, 0x2e, 0x42, 0x6f, 0x74, 0x52, 0x04, 0x62, 0x6f, 0x74, 0x73, 0x22,
	0x4e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x15, 0x0a, 0x06, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22,
	0x59, 0x0a, 0x11, 0x45, 0x64, 0x69, 0x74, 0x42, 0x6f, 0x74, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x76,
	0x34, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x42, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x29, 0x0a, 0x10, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15,
	0x0a, 0x06, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x62, 0x6f, 0x74, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x12, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x42, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x62,
	0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x74,
	0x49, 0x64, 0x22, 0x2d, 0x0a, 0x14, 0x49, 0x6e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x42, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x6f,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x74, 0x49,
	0x64, 0x22, 0x2e, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x6f,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x74, 0x49,
	0x64, 0x22, 0x48, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x76, 0x34, 0x2e, 0x42, 0x6f, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x22, 0x50, 0x0a, 0x18, 0x4c,
	0x65, 0x74, 0x42, 0x6f, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x6f, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x51, 0x0a,
	0x19, 0x4c, 0x65, 0x74, 0x42, 0x6f, 0x74, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x6f,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x74, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64,
	0x22, 0x46, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x6f, 0x74, 0x49, 0x63, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x6f, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x77, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x42,
	0x6f, 0x74, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62,
	0x6f, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x12,
	0x1b, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x01, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06,
	0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x22, 0x39, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x74, 0x4c, 0x6f, 0x67, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x76, 0x34, 0x2e, 0x42, 0x6f, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0x2d, 0x0a, 0x14,
	0x52, 0x65, 0x69, 0x73, 0x73, 0x75, 0x65, 0x42, 0x6f, 0x74, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x42, 0x6f, 0x74, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x32, 0xbf, 0x05, 0x0a, 0x0a, 0x42, 0x6f, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x74, 0x73,
	0x12, 0x12, 0x2e, 0x76, 0x34, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x76, 0x34, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x6f, 0x74, 0x12, 0x12, 0x2e, 0x76, 0x34, 0x2e, 0x50, 0x6f, 0x73, 0x74,
	0x42, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x76, 0x34, 0x2e,
	0x42, 0x6f, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x2a, 0x0a, 0x06, 0x47, 0x65, 0x74,
	0x42, 0x6f, 0x74, 0x12, 0x11, 0x2e, 0x76, 0x34, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x76, 0x34, 0x2e, 0x42, 0x6f, 0x74, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x33, 0x0a, 0x07, 0x45, 0x64, 0x69, 0x74, 0x42, 0x6f, 0x74,
	0x12, 0x15, 0x2e, 0x76, 0x34, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x42, 0x6f, 0x74, 0x52, 0x70, 0x63,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x76, 0x34, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x74, 0x12, 0x14, 0x2e, 0x76, 0x34, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e,
	0x76, 0x34, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x38, 0x0a, 0x0b, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x74, 0x12,
	0x16, 0x2e, 0x76, 0x34, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x76, 0x34, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0d, 0x49, 0x6e,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x74, 0x12, 0x18, 0x2e, 0x76, 0x34,
	0x2e, 0x49, 0x6e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x76, 0x34, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x11, 0x4c, 0x65, 0x74, 0x42,
	0x6f, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1c, 0x2e,
	0x76, 0x34, 0x2e, 0x4c, 0x65, 0x74, 0x42, 0x6f, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x76, 0x34,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46,
	0x0a, 0x12, 0x4c, 0x65, 0x74, 0x42, 0x6f, 0x74, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1d, 0x2e, 0x76, 0x34, 0x2e, 0x4c, 0x65, 0x74, 0x42, 0x6f, 0x74,
	0x4c, 0x65, 0x61, 0x76, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x76, 0x34, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x42, 0x6f, 0x74, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x76, 0x34, 0x2e, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x42, 0x6f, 0x74, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x11, 0x2e, 0x76, 0x34, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x74, 0x4c, 0x6f,
	0x67, 0x73, 0x12, 0x15, 0x2e, 0x76, 0x34, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x74, 0x4c, 0x6f,
	0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x76, 0x34, 0x2e, 0x47,
	0x65, 0x74, 0x42, 0x6f, 0x74, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x35, 0x0a, 0x0a, 0x52, 0x65, 0x69, 0x73, 0x73, 0x75, 0x65, 0x42, 0x6f, 0x74, 0x12,
	0x18, 0x2e, 0x76, 0x34, 0x2e, 0x52, 0x65, 0x69, 0x73, 0x73, 0x75, 0x65, 0x42, 0x6f, 0x74, 0x52,
	0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x76, 0x34, 0x2e, 0x42,
	0x6f, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x72, 0x61, 0x50, 0x74, 0x69, 0x74, 0x65, 0x63,
	0x68, 0x2f, 0x74, 0x72, 0x61, 0x51, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x34, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v4_bot_proto_rawDescOnce sync.Once
	file_v4_bot_proto_rawDescData = file_v4_bot_proto_rawDesc
)

func file_v4_bot_proto_rawDescGZIP() []byte {
	file_v4_bot_proto_rawDescOnce.Do(func() {
		file_v4_bot_proto_rawDescData = protoimpl.X.CompressGZIP(file_v4_bot_proto_rawDescData)
	})
	return file_v4_bot_proto_rawDescData
}

var file_v4_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_v4_bot_proto_goTypes = []interface{}{
	(*Bot)(nil),                       // 0: v4.Bot
	(*BotDetail)(nil),                 // 1: v4.BotDetail
	(*PostBotRequest)(nil),            // 2: v4.PostBotRequest
	(*PatchBotRequest)(nil),           // 3: v4.PatchBotRequest
	(*BotEventLog)(nil),               // 4: v4.BotEventLog
	(*BotJoinChannel)(nil),            // 5: v4.BotJoinChannel
	(*BotLeaveChannel)(nil),           // 6: v4.BotLeaveChannel
	(*ReissueBotTokenRequest)(nil),    // 7: v4.ReissueBotTokenRequest
	(*BotTokens)(nil),                 // 8: v4.BotTokens
	(*GetBotsRequest)(nil),            // 9: v4.GetBotsRequest
	(*GetBotsResponse)(nil),           // 10: v4.GetBotsResponse
	(*GetBotRequest)(nil),             // 11: v4.GetBotRequest
	(*EditBotRpcRequest)(nil),         // 12: v4.EditBotRpcRequest
	(*DeleteBotRequest)(nil),          // 13: v4.DeleteBotRequest
	(*ActivateBotRequest)(nil),        // 14: v4.ActivateBotRequest
	(*InactivateBotRequest)(nil),      // 15: v4.InactivateBotRequest
	(*GetBotChannelsRequest)(nil),     // 16: v4.GetBotChannelsRequest
	(*GetBotChannelsResponse)(nil),    // 17: v4.GetBotChannelsResponse
	(*LetBotJoinChannelRequest)(nil),  // 18: v4.LetBotJoinChannelRequest
	(*LetBotLeaveChannelRequest)(nil), // 19: v4.LetBotLeaveChannelRequest
	(*ChangeBotIconRequest)(nil),      // 20: v4.ChangeBotIconRequest
	(*GetBotLogsRequest)(nil),         // 21: v4.GetBotLogsRequest
	(*GetBotLogsResponse)(nil),        // 22: v4.GetBotLogsResponse
	(*ReissueBotRpcRequest)(nil),      // 23: v4.ReissueBotRpcRequest
	(*GetBotIconRequest)(nil),         // 24: v4.GetBotIconRequest
	(BotMode)(0),                      // 25: v4.BotMode
	(*timestamppb.Timestamp)(nil),     // 26: google.protobuf.Timestamp
	(UserAccountState)(0),             // 27: v4.UserAccountState
	(BotEvent)(0),                     // 28: v4.BotEvent
	(*EmptyResponse)(nil),             // 29: v4.EmptyResponse
}
var file_v4_bot_proto_depIdxs = []int32{
	25, // 0: v4.Bot.mode:type_name -> v4.BotMode
	26, // 1: v4.Bot.created_at:type_name -> google.protobuf.Timestamp
	26, // 2: v4.Bot.updated_at:type_name -> google.protobuf.Timestamp
	27, // 3: v4.Bot.state:type_name -> v4.UserAccountState
	25, // 4: v4.BotDetail.mode:type_name -> v4.BotMode
	26, // 5: v4.BotDetail.created_at:type_name -> google.protobuf.Timestamp
	26, // 6: v4.BotDetail.updated_at:type_name -> google.protobuf.Timestamp
	27, // 7: v4.BotDetail.state:type_name -> v4.UserAccountState
	25, // 8: v4.PostBotRequest.mode:type_name -> v4.BotMode
	25, // 9: v4.PatchBotRequest.mode:type_name -> v4.BotMode
	28, // 10: v4.BotEventLog.event:type_name -> v4.BotEvent
	26, // 11: v4.BotEventLog.datetime:type_name -> google.protobuf.Timestamp
	0,  // 12: v4.GetBotsResponse.bots:type_name -> v4.Bot
	3,  // 13: v4.EditBotRpcRequest.payload:type_name -> v4.PatchBotRequest
	5,  // 14: v4.GetBotChannelsResponse.channels:type_name -> v4.BotJoinChannel
	4,  // 15: v4.GetBotLogsResponse.logs:type_name -> v4.BotEventLog
	9,  // 16: v4.BotService.GetBots:input_type -> v4.GetBotsRequest
	2,  // 17: v4.BotService.CreateBot:input_type -> v4.PostBotRequest
	11, // 18: v4.BotService.GetBot:input_type -> v4.GetBotRequest
	12, // 19: v4.BotService.EditBot:input_type -> v4.EditBotRpcRequest
	13, // 20: v4.BotService.DeleteBot:input_type -> v4.DeleteBotRequest
	14, // 21: v4.BotService.ActivateBot:input_type -> v4.ActivateBotRequest
	15, // 22: v4.BotService.InactivateBot:input_type -> v4.InactivateBotRequest
	18, // 23: v4.BotService.LetBotJoinChannel:input_type -> v4.LetBotJoinChannelRequest
	19, // 24: v4.BotService.LetBotLeaveChannel:input_type -> v4.LetBotLeaveChannelRequest
	20, // 25: v4.BotService.ChangeBotIcon:input_type -> v4.ChangeBotIconRequest
	21, // 26: v4.BotService.GetBotLogs:input_type -> v4.GetBotLogsRequest
	23, // 27: v4.BotService.ReissueBot:input_type -> v4.ReissueBotRpcRequest
	10, // 28: v4.BotService.GetBots:output_type -> v4.GetBotsResponse
	1,  // 29: v4.BotService.CreateBot:output_type -> v4.BotDetail
	1,  // 30: v4.BotService.GetBot:output_type -> v4.BotDetail
	29, // 31: v4.BotService.EditBot:output_type -> v4.EmptyResponse
	29, // 32: v4.BotService.DeleteBot:output_type -> v4.EmptyResponse
	29, // 33: v4.BotService.ActivateBot:output_type -> v4.EmptyResponse
	29, // 34: v4.BotService.InactivateBot:output_type -> v4.EmptyResponse
	29, // 35: v4.BotService.LetBotJoinChannel:output_type -> v4.EmptyResponse
	29, // 36: v4.BotService.LetBotLeaveChannel:output_type -> v4.EmptyResponse
	29, // 37: v4.BotService.ChangeBotIcon:output_type -> v4.EmptyResponse
	22, // 38: v4.BotService.GetBotLogs:output_type -> v4.GetBotLogsResponse
	8,  // 39: v4.BotService.ReissueBot:output_type -> v4.BotTokens
	28, // [28:40] is the sub-list for method output_type
	16, // [16:28] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_v4_bot_proto_init() }
func file_v4_bot_proto_init() {
	if File_v4_bot_proto != nil {
		return
	}
	file_v4_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v4_bot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostBotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchBotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotEventLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotJoinChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotLeaveChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReissueBotTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotTokens); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBotsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBotsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditBotRpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivateBotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InactivateBotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBotChannelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBotChannelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LetBotJoinChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LetBotLeaveChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeBotIconRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBotLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBotLogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReissueBotRpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_bot_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBotIconRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v4_bot_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_v4_bot_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_v4_bot_proto_msgTypes[11].OneofWrappers = []interface{}{}
	file_v4_bot_proto_msgTypes[21].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v4_bot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v4_bot_proto_goTypes,
		DependencyIndexes: file_v4_bot_proto_depIdxs,
		MessageInfos:      file_v4_bot_proto_msgTypes,
	}.Build()
	File_v4_bot_proto = out.File
	file_v4_bot_proto_rawDesc = nil
	file_v4_bot_proto_goTypes = nil
	file_v4_bot_proto_depIdxs = nil
}
