// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: v4/bot.proto

package v4

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BotService_GetBots_FullMethodName            = "/v4.BotService/GetBots"
	BotService_CreateBot_FullMethodName          = "/v4.BotService/CreateBot"
	BotService_GetBot_FullMethodName             = "/v4.BotService/GetBot"
	BotService_EditBot_FullMethodName            = "/v4.BotService/EditBot"
	BotService_DeleteBot_FullMethodName          = "/v4.BotService/DeleteBot"
	BotService_ActivateBot_FullMethodName        = "/v4.BotService/ActivateBot"
	BotService_InactivateBot_FullMethodName      = "/v4.BotService/InactivateBot"
	BotService_LetBotJoinChannel_FullMethodName  = "/v4.BotService/LetBotJoinChannel"
	BotService_LetBotLeaveChannel_FullMethodName = "/v4.BotService/LetBotLeaveChannel"
	BotService_ChangeBotIcon_FullMethodName      = "/v4.BotService/ChangeBotIcon"
	BotService_GetBotLogs_FullMethodName         = "/v4.BotService/GetBotLogs"
	BotService_ReissueBot_FullMethodName         = "/v4.BotService/ReissueBot"
)

// BotServiceClient is the client API for BotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BotServiceClient interface {
	// BOTのリストを取得
	GetBots(ctx context.Context, in *GetBotsRequest, opts ...grpc.CallOption) (*GetBotsResponse, error)
	// BOTを作成
	CreateBot(ctx context.Context, in *PostBotRequest, opts ...grpc.CallOption) (*BotDetail, error)
	// BOT情報を取得
	GetBot(ctx context.Context, in *GetBotRequest, opts ...grpc.CallOption) (*BotDetail, error)
	// BOT情報を変更
	EditBot(ctx context.Context, in *EditBotRpcRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// BOTを削除
	DeleteBot(ctx context.Context, in *DeleteBotRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// BOTを有効化
	ActivateBot(ctx context.Context, in *ActivateBotRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// BOTを無効化
	InactivateBot(ctx context.Context, in *InactivateBotRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// BOTをチャンネルに参加させる
	LetBotJoinChannel(ctx context.Context, in *LetBotJoinChannelRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// BOTをチャンネルから退出させる
	LetBotLeaveChannel(ctx context.Context, in *LetBotLeaveChannelRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// BOTのアイコン画像を変更
	ChangeBotIcon(ctx context.Context, in *ChangeBotIconRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// BOTのイベントログを取得
	GetBotLogs(ctx context.Context, in *GetBotLogsRequest, opts ...grpc.CallOption) (*GetBotLogsResponse, error)
	// BOTのトークンを再発行
	ReissueBot(ctx context.Context, in *ReissueBotRpcRequest, opts ...grpc.CallOption) (*BotTokens, error)
}

type botServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBotServiceClient(cc grpc.ClientConnInterface) BotServiceClient {
	return &botServiceClient{cc}
}

func (c *botServiceClient) GetBots(ctx context.Context, in *GetBotsRequest, opts ...grpc.CallOption) (*GetBotsResponse, error) {
	out := new(GetBotsResponse)
	err := c.cc.Invoke(ctx, BotService_GetBots_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) CreateBot(ctx context.Context, in *PostBotRequest, opts ...grpc.CallOption) (*BotDetail, error) {
	out := new(BotDetail)
	err := c.cc.Invoke(ctx, BotService_CreateBot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) GetBot(ctx context.Context, in *GetBotRequest, opts ...grpc.CallOption) (*BotDetail, error) {
	out := new(BotDetail)
	err := c.cc.Invoke(ctx, BotService_GetBot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) EditBot(ctx context.Context, in *EditBotRpcRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, BotService_EditBot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) DeleteBot(ctx context.Context, in *DeleteBotRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, BotService_DeleteBot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) ActivateBot(ctx context.Context, in *ActivateBotRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, BotService_ActivateBot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) InactivateBot(ctx context.Context, in *InactivateBotRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, BotService_InactivateBot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) LetBotJoinChannel(ctx context.Context, in *LetBotJoinChannelRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, BotService_LetBotJoinChannel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) LetBotLeaveChannel(ctx context.Context, in *LetBotLeaveChannelRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, BotService_LetBotLeaveChannel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) ChangeBotIcon(ctx context.Context, in *ChangeBotIconRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, BotService_ChangeBotIcon_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) GetBotLogs(ctx context.Context, in *GetBotLogsRequest, opts ...grpc.CallOption) (*GetBotLogsResponse, error) {
	out := new(GetBotLogsResponse)
	err := c.cc.Invoke(ctx, BotService_GetBotLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) ReissueBot(ctx context.Context, in *ReissueBotRpcRequest, opts ...grpc.CallOption) (*BotTokens, error) {
	out := new(BotTokens)
	err := c.cc.Invoke(ctx, BotService_ReissueBot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotServiceServer is the server API for BotService service.
// All implementations must embed UnimplementedBotServiceServer
// for forward compatibility
type BotServiceServer interface {
	// BOTのリストを取得
	GetBots(context.Context, *GetBotsRequest) (*GetBotsResponse, error)
	// BOTを作成
	CreateBot(context.Context, *PostBotRequest) (*BotDetail, error)
	// BOT情報を取得
	GetBot(context.Context, *GetBotRequest) (*BotDetail, error)
	// BOT情報を変更
	EditBot(context.Context, *EditBotRpcRequest) (*EmptyResponse, error)
	// BOTを削除
	DeleteBot(context.Context, *DeleteBotRequest) (*EmptyResponse, error)
	// BOTを有効化
	ActivateBot(context.Context, *ActivateBotRequest) (*EmptyResponse, error)
	// BOTを無効化
	InactivateBot(context.Context, *InactivateBotRequest) (*EmptyResponse, error)
	// BOTをチャンネルに参加させる
	LetBotJoinChannel(context.Context, *LetBotJoinChannelRequest) (*EmptyResponse, error)
	// BOTをチャンネルから退出させる
	LetBotLeaveChannel(context.Context, *LetBotLeaveChannelRequest) (*EmptyResponse, error)
	// BOTのアイコン画像を変更
	ChangeBotIcon(context.Context, *ChangeBotIconRequest) (*EmptyResponse, error)
	// BOTのイベントログを取得
	GetBotLogs(context.Context, *GetBotLogsRequest) (*GetBotLogsResponse, error)
	// BOTのトークンを再発行
	ReissueBot(context.Context, *ReissueBotRpcRequest) (*BotTokens, error)
	mustEmbedUnimplementedBotServiceServer()
}

// UnimplementedBotServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBotServiceServer struct {
}

func (UnimplementedBotServiceServer) GetBots(context.Context, *GetBotsRequest) (*GetBotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBots not implemented")
}
func (UnimplementedBotServiceServer) CreateBot(context.Context, *PostBotRequest) (*BotDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBot not implemented")
}
func (UnimplementedBotServiceServer) GetBot(context.Context, *GetBotRequest) (*BotDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBot not implemented")
}
func (UnimplementedBotServiceServer) EditBot(context.Context, *EditBotRpcRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditBot not implemented")
}
func (UnimplementedBotServiceServer) DeleteBot(context.Context, *DeleteBotRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBot not implemented")
}
func (UnimplementedBotServiceServer) ActivateBot(context.Context, *ActivateBotRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateBot not implemented")
}
func (UnimplementedBotServiceServer) InactivateBot(context.Context, *InactivateBotRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InactivateBot not implemented")
}
func (UnimplementedBotServiceServer) LetBotJoinChannel(context.Context, *LetBotJoinChannelRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LetBotJoinChannel not implemented")
}
func (UnimplementedBotServiceServer) LetBotLeaveChannel(context.Context, *LetBotLeaveChannelRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LetBotLeaveChannel not implemented")
}
func (UnimplementedBotServiceServer) ChangeBotIcon(context.Context, *ChangeBotIconRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeBotIcon not implemented")
}
func (UnimplementedBotServiceServer) GetBotLogs(context.Context, *GetBotLogsRequest) (*GetBotLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBotLogs not implemented")
}
func (UnimplementedBotServiceServer) ReissueBot(context.Context, *ReissueBotRpcRequest) (*BotTokens, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReissueBot not implemented")
}
func (UnimplementedBotServiceServer) mustEmbedUnimplementedBotServiceServer() {}

// UnsafeBotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotServiceServer will
// result in compilation errors.
type UnsafeBotServiceServer interface {
	mustEmbedUnimplementedBotServiceServer()
}

func RegisterBotServiceServer(s grpc.ServiceRegistrar, srv BotServiceServer) {
	s.RegisterService(&BotService_ServiceDesc, srv)
}

func _BotService_GetBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).GetBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_GetBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).GetBots(ctx, req.(*GetBotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_CreateBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).CreateBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_CreateBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).CreateBot(ctx, req.(*PostBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_GetBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).GetBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_GetBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).GetBot(ctx, req.(*GetBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_EditBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditBotRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).EditBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_EditBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).EditBot(ctx, req.(*EditBotRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_DeleteBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).DeleteBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_DeleteBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).DeleteBot(ctx, req.(*DeleteBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_ActivateBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).ActivateBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_ActivateBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).ActivateBot(ctx, req.(*ActivateBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_InactivateBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InactivateBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).InactivateBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_InactivateBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).InactivateBot(ctx, req.(*InactivateBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_LetBotJoinChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LetBotJoinChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).LetBotJoinChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_LetBotJoinChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).LetBotJoinChannel(ctx, req.(*LetBotJoinChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_LetBotLeaveChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LetBotLeaveChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).LetBotLeaveChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_LetBotLeaveChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).LetBotLeaveChannel(ctx, req.(*LetBotLeaveChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_ChangeBotIcon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeBotIconRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).ChangeBotIcon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_ChangeBotIcon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).ChangeBotIcon(ctx, req.(*ChangeBotIconRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_GetBotLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).GetBotLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_GetBotLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).GetBotLogs(ctx, req.(*GetBotLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_ReissueBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReissueBotRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).ReissueBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_ReissueBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).ReissueBot(ctx, req.(*ReissueBotRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BotService_ServiceDesc is the grpc.ServiceDesc for BotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v4.BotService",
	HandlerType: (*BotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBots",
			Handler:    _BotService_GetBots_Handler,
		},
		{
			MethodName: "CreateBot",
			Handler:    _BotService_CreateBot_Handler,
		},
		{
			MethodName: "GetBot",
			Handler:    _BotService_GetBot_Handler,
		},
		{
			MethodName: "EditBot",
			Handler:    _BotService_EditBot_Handler,
		},
		{
			MethodName: "DeleteBot",
			Handler:    _BotService_DeleteBot_Handler,
		},
		{
			MethodName: "ActivateBot",
			Handler:    _BotService_ActivateBot_Handler,
		},
		{
			MethodName: "InactivateBot",
			Handler:    _BotService_InactivateBot_Handler,
		},
		{
			MethodName: "LetBotJoinChannel",
			Handler:    _BotService_LetBotJoinChannel_Handler,
		},
		{
			MethodName: "LetBotLeaveChannel",
			Handler:    _BotService_LetBotLeaveChannel_Handler,
		},
		{
			MethodName: "ChangeBotIcon",
			Handler:    _BotService_ChangeBotIcon_Handler,
		},
		{
			MethodName: "GetBotLogs",
			Handler:    _BotService_GetBotLogs_Handler,
		},
		{
			MethodName: "ReissueBot",
			Handler:    _BotService_ReissueBot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v4/bot.proto",
}
