// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: v4/clip.proto

package v4

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ClipService_GetClipFolders_FullMethodName          = "/v4.ClipService/GetClipFolders"
	ClipService_CreateClipFolder_FullMethodName        = "/v4.ClipService/CreateClipFolder"
	ClipService_GetClipFolder_FullMethodName           = "/v4.ClipService/GetClipFolder"
	ClipService_EditClipFolder_FullMethodName          = "/v4.ClipService/EditClipFolder"
	ClipService_DeleteClipFolder_FullMethodName        = "/v4.ClipService/DeleteClipFolder"
	ClipService_GetMessagesInClipFolder_FullMethodName = "/v4.ClipService/GetMessagesInClipFolder"
	ClipService_ClipMessage_FullMethodName             = "/v4.ClipService/ClipMessage"
	ClipService_UnclipMessage_FullMethodName           = "/v4.ClipService/UnclipMessage"
)

// ClipServiceClient is the client API for ClipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClipServiceClient interface {
	// クリップフォルダのリストを取得
	GetClipFolders(ctx context.Context, in *GetClipFoldersRequest, opts ...grpc.CallOption) (*GetClipFoldersResponse, error)
	// クリップフォルダを作成
	CreateClipFolder(ctx context.Context, in *PostClipFolderRequest, opts ...grpc.CallOption) (*ClipFolder, error)
	// クリップフォルダ情報を取得
	GetClipFolder(ctx context.Context, in *GetClipFolderRequest, opts ...grpc.CallOption) (*ClipFolder, error)
	// クリップフォルダ情報を編集
	EditClipFolder(ctx context.Context, in *PatchClipFolderRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// クリップフォルダを削除
	DeleteClipFolder(ctx context.Context, in *DeleteClipFolderRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// フォルダ内のクリップのリストを取得
	GetMessagesInClipFolder(ctx context.Context, in *GetMessagesInClipFolderRequest, opts ...grpc.CallOption) (*GetMessagesInClipFolderResponse, error)
	// メッセージをクリップフォルダに追加
	ClipMessage(ctx context.Context, in *PostMessageClipRequest, opts ...grpc.CallOption) (*ClippedMessage, error)
	// メッセージのクリップを削除
	UnclipMessage(ctx context.Context, in *UnclipMessageRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type clipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClipServiceClient(cc grpc.ClientConnInterface) ClipServiceClient {
	return &clipServiceClient{cc}
}

func (c *clipServiceClient) GetClipFolders(ctx context.Context, in *GetClipFoldersRequest, opts ...grpc.CallOption) (*GetClipFoldersResponse, error) {
	out := new(GetClipFoldersResponse)
	err := c.cc.Invoke(ctx, ClipService_GetClipFolders_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clipServiceClient) CreateClipFolder(ctx context.Context, in *PostClipFolderRequest, opts ...grpc.CallOption) (*ClipFolder, error) {
	out := new(ClipFolder)
	err := c.cc.Invoke(ctx, ClipService_CreateClipFolder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clipServiceClient) GetClipFolder(ctx context.Context, in *GetClipFolderRequest, opts ...grpc.CallOption) (*ClipFolder, error) {
	out := new(ClipFolder)
	err := c.cc.Invoke(ctx, ClipService_GetClipFolder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clipServiceClient) EditClipFolder(ctx context.Context, in *PatchClipFolderRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, ClipService_EditClipFolder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clipServiceClient) DeleteClipFolder(ctx context.Context, in *DeleteClipFolderRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, ClipService_DeleteClipFolder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clipServiceClient) GetMessagesInClipFolder(ctx context.Context, in *GetMessagesInClipFolderRequest, opts ...grpc.CallOption) (*GetMessagesInClipFolderResponse, error) {
	out := new(GetMessagesInClipFolderResponse)
	err := c.cc.Invoke(ctx, ClipService_GetMessagesInClipFolder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clipServiceClient) ClipMessage(ctx context.Context, in *PostMessageClipRequest, opts ...grpc.CallOption) (*ClippedMessage, error) {
	out := new(ClippedMessage)
	err := c.cc.Invoke(ctx, ClipService_ClipMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clipServiceClient) UnclipMessage(ctx context.Context, in *UnclipMessageRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, ClipService_UnclipMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClipServiceServer is the server API for ClipService service.
// All implementations must embed UnimplementedClipServiceServer
// for forward compatibility
type ClipServiceServer interface {
	// クリップフォルダのリストを取得
	GetClipFolders(context.Context, *GetClipFoldersRequest) (*GetClipFoldersResponse, error)
	// クリップフォルダを作成
	CreateClipFolder(context.Context, *PostClipFolderRequest) (*ClipFolder, error)
	// クリップフォルダ情報を取得
	GetClipFolder(context.Context, *GetClipFolderRequest) (*ClipFolder, error)
	// クリップフォルダ情報を編集
	EditClipFolder(context.Context, *PatchClipFolderRequest) (*EmptyResponse, error)
	// クリップフォルダを削除
	DeleteClipFolder(context.Context, *DeleteClipFolderRequest) (*EmptyResponse, error)
	// フォルダ内のクリップのリストを取得
	GetMessagesInClipFolder(context.Context, *GetMessagesInClipFolderRequest) (*GetMessagesInClipFolderResponse, error)
	// メッセージをクリップフォルダに追加
	ClipMessage(context.Context, *PostMessageClipRequest) (*ClippedMessage, error)
	// メッセージのクリップを削除
	UnclipMessage(context.Context, *UnclipMessageRequest) (*EmptyResponse, error)
	mustEmbedUnimplementedClipServiceServer()
}

// UnimplementedClipServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClipServiceServer struct {
}

func (UnimplementedClipServiceServer) GetClipFolders(context.Context, *GetClipFoldersRequest) (*GetClipFoldersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClipFolders not implemented")
}
func (UnimplementedClipServiceServer) CreateClipFolder(context.Context, *PostClipFolderRequest) (*ClipFolder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClipFolder not implemented")
}
func (UnimplementedClipServiceServer) GetClipFolder(context.Context, *GetClipFolderRequest) (*ClipFolder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClipFolder not implemented")
}
func (UnimplementedClipServiceServer) EditClipFolder(context.Context, *PatchClipFolderRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditClipFolder not implemented")
}
func (UnimplementedClipServiceServer) DeleteClipFolder(context.Context, *DeleteClipFolderRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteClipFolder not implemented")
}
func (UnimplementedClipServiceServer) GetMessagesInClipFolder(context.Context, *GetMessagesInClipFolderRequest) (*GetMessagesInClipFolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessagesInClipFolder not implemented")
}
func (UnimplementedClipServiceServer) ClipMessage(context.Context, *PostMessageClipRequest) (*ClippedMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClipMessage not implemented")
}
func (UnimplementedClipServiceServer) UnclipMessage(context.Context, *UnclipMessageRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnclipMessage not implemented")
}
func (UnimplementedClipServiceServer) mustEmbedUnimplementedClipServiceServer() {}

// UnsafeClipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClipServiceServer will
// result in compilation errors.
type UnsafeClipServiceServer interface {
	mustEmbedUnimplementedClipServiceServer()
}

func RegisterClipServiceServer(s grpc.ServiceRegistrar, srv ClipServiceServer) {
	s.RegisterService(&ClipService_ServiceDesc, srv)
}

func _ClipService_GetClipFolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClipFoldersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipServiceServer).GetClipFolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClipService_GetClipFolders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipServiceServer).GetClipFolders(ctx, req.(*GetClipFoldersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClipService_CreateClipFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostClipFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipServiceServer).CreateClipFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClipService_CreateClipFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipServiceServer).CreateClipFolder(ctx, req.(*PostClipFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClipService_GetClipFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClipFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipServiceServer).GetClipFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClipService_GetClipFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipServiceServer).GetClipFolder(ctx, req.(*GetClipFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClipService_EditClipFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchClipFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipServiceServer).EditClipFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClipService_EditClipFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipServiceServer).EditClipFolder(ctx, req.(*PatchClipFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClipService_DeleteClipFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClipFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipServiceServer).DeleteClipFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClipService_DeleteClipFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipServiceServer).DeleteClipFolder(ctx, req.(*DeleteClipFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClipService_GetMessagesInClipFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesInClipFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipServiceServer).GetMessagesInClipFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClipService_GetMessagesInClipFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipServiceServer).GetMessagesInClipFolder(ctx, req.(*GetMessagesInClipFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClipService_ClipMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMessageClipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipServiceServer).ClipMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClipService_ClipMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipServiceServer).ClipMessage(ctx, req.(*PostMessageClipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClipService_UnclipMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnclipMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipServiceServer).UnclipMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClipService_UnclipMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipServiceServer).UnclipMessage(ctx, req.(*UnclipMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClipService_ServiceDesc is the grpc.ServiceDesc for ClipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v4.ClipService",
	HandlerType: (*ClipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClipFolders",
			Handler:    _ClipService_GetClipFolders_Handler,
		},
		{
			MethodName: "CreateClipFolder",
			Handler:    _ClipService_CreateClipFolder_Handler,
		},
		{
			MethodName: "GetClipFolder",
			Handler:    _ClipService_GetClipFolder_Handler,
		},
		{
			MethodName: "EditClipFolder",
			Handler:    _ClipService_EditClipFolder_Handler,
		},
		{
			MethodName: "DeleteClipFolder",
			Handler:    _ClipService_DeleteClipFolder_Handler,
		},
		{
			MethodName: "GetMessagesInClipFolder",
			Handler:    _ClipService_GetMessagesInClipFolder_Handler,
		},
		{
			MethodName: "ClipMessage",
			Handler:    _ClipService_ClipMessage_Handler,
		},
		{
			MethodName: "UnclipMessage",
			Handler:    _ClipService_UnclipMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v4/clip.proto",
}
