// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: v4/notification.proto

package v4

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// デバイス登録リクエスト (me.protoのPostMyFCMDeviceRequestと重複する可能性があるため注意)
type RegisterDeviceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// FCMのデバイストークン
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *RegisterDeviceRequest) Reset() {
	*x = RegisterDeviceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_notification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceRequest) ProtoMessage() {}

func (x *RegisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_notification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_v4_notification_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterDeviceRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 未読チャンネルのリストを取得するリクエスト (me.protoのGetMyUnreadChannelsRequestと重複)
type GetMyUnreadChannelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMyUnreadChannelsRequest) Reset() {
	*x = GetMyUnreadChannelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_notification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyUnreadChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyUnreadChannelsRequest) ProtoMessage() {}

func (x *GetMyUnreadChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_notification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyUnreadChannelsRequest.ProtoReflect.Descriptor instead.
func (*GetMyUnreadChannelsRequest) Descriptor() ([]byte, []int) {
	return file_v4_notification_proto_rawDescGZIP(), []int{1}
}

// 未読チャンネル情報 (me.protoのUnreadChannelと重複)
type UnreadChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId       string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Count           int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Noticeable      bool                   `protobuf:"varint,3,opt,name=noticeable,proto3" json:"noticeable,omitempty"`
	Since           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	NewestMessageId string                 `protobuf:"bytes,6,opt,name=newest_message_id,json=newestMessageId,proto3" json:"newest_message_id,omitempty"`
}

func (x *UnreadChannel) Reset() {
	*x = UnreadChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_notification_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnreadChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadChannel) ProtoMessage() {}

func (x *UnreadChannel) ProtoReflect() protoreflect.Message {
	mi := &file_v4_notification_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadChannel.ProtoReflect.Descriptor instead.
func (*UnreadChannel) Descriptor() ([]byte, []int) {
	return file_v4_notification_proto_rawDescGZIP(), []int{2}
}

func (x *UnreadChannel) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *UnreadChannel) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UnreadChannel) GetNoticeable() bool {
	if x != nil {
		return x.Noticeable
	}
	return false
}

func (x *UnreadChannel) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *UnreadChannel) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UnreadChannel) GetNewestMessageId() string {
	if x != nil {
		return x.NewestMessageId
	}
	return ""
}

type GetMyUnreadChannelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnreadChannels []*UnreadChannel `protobuf:"bytes,1,rep,name=unread_channels,json=unreadChannels,proto3" json:"unread_channels,omitempty"`
}

func (x *GetMyUnreadChannelsResponse) Reset() {
	*x = GetMyUnreadChannelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_notification_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyUnreadChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyUnreadChannelsResponse) ProtoMessage() {}

func (x *GetMyUnreadChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v4_notification_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyUnreadChannelsResponse.ProtoReflect.Descriptor instead.
func (*GetMyUnreadChannelsResponse) Descriptor() ([]byte, []int) {
	return file_v4_notification_proto_rawDescGZIP(), []int{3}
}

func (x *GetMyUnreadChannelsResponse) GetUnreadChannels() []*UnreadChannel {
	if x != nil {
		return x.UnreadChannels
	}
	return nil
}

// チャンネルの未読状態を解消するリクエスト (me.protoのReadMyChannelRequestと重複)
type ReadChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (x *ReadChannelRequest) Reset() {
	*x = ReadChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_notification_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChannelRequest) ProtoMessage() {}

func (x *ReadChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_notification_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChannelRequest.ProtoReflect.Descriptor instead.
func (*ReadChannelRequest) Descriptor() ([]byte, []int) {
	return file_v4_notification_proto_rawDescGZIP(), []int{4}
}

func (x *ReadChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

// チャンネル購読レベル設定リクエスト (me.protoのPutChannelSubscribeLevelRequestと重複)
type SetChannelSubscribeLevelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId string                `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`       // path parameter
	Level     ChannelSubscribeLevel `protobuf:"varint,2,opt,name=level,proto3,enum=v4.ChannelSubscribeLevel" json:"level,omitempty"` // Removed common.
}

func (x *SetChannelSubscribeLevelRequest) Reset() {
	*x = SetChannelSubscribeLevelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_notification_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetChannelSubscribeLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetChannelSubscribeLevelRequest) ProtoMessage() {}

func (x *SetChannelSubscribeLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_notification_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetChannelSubscribeLevelRequest.ProtoReflect.Descriptor instead.
func (*SetChannelSubscribeLevelRequest) Descriptor() ([]byte, []int) {
	return file_v4_notification_proto_rawDescGZIP(), []int{5}
}

func (x *SetChannelSubscribeLevelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SetChannelSubscribeLevelRequest) GetLevel() ChannelSubscribeLevel {
	if x != nil {
		return x.Level
	}
	return ChannelSubscribeLevel_CHANNEL_SUBSCRIBE_LEVEL_UNSPECIFIED
}

// チャンネル購読情報 (me.protoのChannelSubscriptionと重複)
type ChannelSubscription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId string                `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Level     ChannelSubscribeLevel `protobuf:"varint,2,opt,name=level,proto3,enum=v4.ChannelSubscribeLevel" json:"level,omitempty"` // Removed common.
}

func (x *ChannelSubscription) Reset() {
	*x = ChannelSubscription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_notification_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelSubscription) ProtoMessage() {}

func (x *ChannelSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_v4_notification_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelSubscription.ProtoReflect.Descriptor instead.
func (*ChannelSubscription) Descriptor() ([]byte, []int) {
	return file_v4_notification_proto_rawDescGZIP(), []int{6}
}

func (x *ChannelSubscription) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelSubscription) GetLevel() ChannelSubscribeLevel {
	if x != nil {
		return x.Level
	}
	return ChannelSubscribeLevel_CHANNEL_SUBSCRIBE_LEVEL_UNSPECIFIED
}

type GetChannelSubscriptionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetChannelSubscriptionsRequest) Reset() {
	*x = GetChannelSubscriptionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_notification_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChannelSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelSubscriptionsRequest) ProtoMessage() {}

func (x *GetChannelSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_notification_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetChannelSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_v4_notification_proto_rawDescGZIP(), []int{7}
}

type GetChannelSubscriptionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subscriptions []*ChannelSubscription `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
}

func (x *GetChannelSubscriptionsResponse) Reset() {
	*x = GetChannelSubscriptionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_notification_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChannelSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelSubscriptionsResponse) ProtoMessage() {}

func (x *GetChannelSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v4_notification_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetChannelSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_v4_notification_proto_rawDescGZIP(), []int{8}
}

func (x *GetChannelSubscriptionsResponse) GetSubscriptions() []*ChannelSubscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type GetMyChannelSubscriptionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMyChannelSubscriptionsRequest) Reset() {
	*x = GetMyChannelSubscriptionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_notification_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyChannelSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyChannelSubscriptionsRequest) ProtoMessage() {}

func (x *GetMyChannelSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v4_notification_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyChannelSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetMyChannelSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_v4_notification_proto_rawDescGZIP(), []int{9}
}

type GetMyChannelSubscriptionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subscriptions []*ChannelSubscription `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
}

func (x *GetMyChannelSubscriptionsResponse) Reset() {
	*x = GetMyChannelSubscriptionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v4_notification_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyChannelSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyChannelSubscriptionsResponse) ProtoMessage() {}

func (x *GetMyChannelSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v4_notification_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyChannelSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetMyChannelSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_v4_notification_proto_rawDescGZIP(), []int{10}
}

func (x *GetMyChannelSubscriptionsResponse) GetSubscriptions() []*ChannelSubscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

var File_v4_notification_proto protoreflect.FileDescriptor

var file_v4_notification_proto_rawDesc = []byte{
	0x0a, 0x15, 0x76, 0x34, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x34, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x76, 0x34,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a,
	0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x1c, 0x0a, 0x1a,
	0x47, 0x65, 0x74, 0x4d, 0x79, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xfd, 0x01, 0x0a, 0x0d, 0x55,
	0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x61, 0x62, 0x6c,
	0x65, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x73, 0x69,
	0x6e, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x2a,
	0x0a, 0x11, 0x6e, 0x65, 0x77, 0x65, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6e, 0x65, 0x77, 0x65, 0x73,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x59, 0x0a, 0x1b, 0x47, 0x65,
	0x74, 0x4d, 0x79, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0f, 0x75, 0x6e, 0x72,
	0x65, 0x61, 0x64, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x34, 0x2e, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x0e, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x22, 0x33, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x71, 0x0a, 0x1f, 0x53, 0x65,
	0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x76, 0x34,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x65, 0x0a,
	0x13, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x19, 0x2e, 0x76, 0x34, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x22, 0x20, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x60, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x73, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x76, 0x34, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x22, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x4d,
	0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x62, 0x0a, 0x21,
	0x47, 0x65, 0x74, 0x4d, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x34, 0x2e, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x32, 0xaa, 0x03, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d,
	0x79, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x12,
	0x1e, 0x2e, 0x76, 0x34, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x76, 0x34, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3a, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x12, 0x16, 0x2e, 0x76, 0x34, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x76, 0x34, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x1a,
	0x53, 0x65, 0x74, 0x4d, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x23, 0x2e, 0x76, 0x34, 0x2e,
	0x53, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x11, 0x2e, 0x76, 0x34, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x41, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x43,
	0x4d, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x19, 0x2e, 0x76, 0x34, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x76, 0x34, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x22, 0x2e, 0x76, 0x34, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x76, 0x34, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x34, 0x5a,
	0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x72, 0x61, 0x50,
	0x74, 0x69, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x74, 0x72, 0x61, 0x51, 0x2f, 0x69, 0x6e, 0x66, 0x72,
	0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x76, 0x34, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v4_notification_proto_rawDescOnce sync.Once
	file_v4_notification_proto_rawDescData = file_v4_notification_proto_rawDesc
)

func file_v4_notification_proto_rawDescGZIP() []byte {
	file_v4_notification_proto_rawDescOnce.Do(func() {
		file_v4_notification_proto_rawDescData = protoimpl.X.CompressGZIP(file_v4_notification_proto_rawDescData)
	})
	return file_v4_notification_proto_rawDescData
}

var file_v4_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_v4_notification_proto_goTypes = []interface{}{
	(*RegisterDeviceRequest)(nil),             // 0: v4.RegisterDeviceRequest
	(*GetMyUnreadChannelsRequest)(nil),        // 1: v4.GetMyUnreadChannelsRequest
	(*UnreadChannel)(nil),                     // 2: v4.UnreadChannel
	(*GetMyUnreadChannelsResponse)(nil),       // 3: v4.GetMyUnreadChannelsResponse
	(*ReadChannelRequest)(nil),                // 4: v4.ReadChannelRequest
	(*SetChannelSubscribeLevelRequest)(nil),   // 5: v4.SetChannelSubscribeLevelRequest
	(*ChannelSubscription)(nil),               // 6: v4.ChannelSubscription
	(*GetChannelSubscriptionsRequest)(nil),    // 7: v4.GetChannelSubscriptionsRequest
	(*GetChannelSubscriptionsResponse)(nil),   // 8: v4.GetChannelSubscriptionsResponse
	(*GetMyChannelSubscriptionsRequest)(nil),  // 9: v4.GetMyChannelSubscriptionsRequest
	(*GetMyChannelSubscriptionsResponse)(nil), // 10: v4.GetMyChannelSubscriptionsResponse
	(*timestamppb.Timestamp)(nil),             // 11: google.protobuf.Timestamp
	(ChannelSubscribeLevel)(0),                // 12: v4.ChannelSubscribeLevel
	(*EmptyResponse)(nil),                     // 13: v4.EmptyResponse
}
var file_v4_notification_proto_depIdxs = []int32{
	11, // 0: v4.UnreadChannel.since:type_name -> google.protobuf.Timestamp
	11, // 1: v4.UnreadChannel.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 2: v4.GetMyUnreadChannelsResponse.unread_channels:type_name -> v4.UnreadChannel
	12, // 3: v4.SetChannelSubscribeLevelRequest.level:type_name -> v4.ChannelSubscribeLevel
	12, // 4: v4.ChannelSubscription.level:type_name -> v4.ChannelSubscribeLevel
	6,  // 5: v4.GetChannelSubscriptionsResponse.subscriptions:type_name -> v4.ChannelSubscription
	6,  // 6: v4.GetMyChannelSubscriptionsResponse.subscriptions:type_name -> v4.ChannelSubscription
	1,  // 7: v4.NotificationService.GetMyUnreadChannels:input_type -> v4.GetMyUnreadChannelsRequest
	4,  // 8: v4.NotificationService.ReadMyChannel:input_type -> v4.ReadChannelRequest
	5,  // 9: v4.NotificationService.SetMyChannelSubscribeLevel:input_type -> v4.SetChannelSubscribeLevelRequest
	0,  // 10: v4.NotificationService.RegisterFCMDevice:input_type -> v4.RegisterDeviceRequest
	7,  // 11: v4.NotificationService.GetMyChannelSubscriptions:input_type -> v4.GetChannelSubscriptionsRequest
	3,  // 12: v4.NotificationService.GetMyUnreadChannels:output_type -> v4.GetMyUnreadChannelsResponse
	13, // 13: v4.NotificationService.ReadMyChannel:output_type -> v4.EmptyResponse
	13, // 14: v4.NotificationService.SetMyChannelSubscribeLevel:output_type -> v4.EmptyResponse
	13, // 15: v4.NotificationService.RegisterFCMDevice:output_type -> v4.EmptyResponse
	10, // 16: v4.NotificationService.GetMyChannelSubscriptions:output_type -> v4.GetMyChannelSubscriptionsResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_v4_notification_proto_init() }
func file_v4_notification_proto_init() {
	if File_v4_notification_proto != nil {
		return
	}
	file_v4_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v4_notification_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterDeviceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_notification_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyUnreadChannelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_notification_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnreadChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_notification_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyUnreadChannelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_notification_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_notification_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetChannelSubscribeLevelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_notification_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelSubscription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_notification_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChannelSubscriptionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_notification_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChannelSubscriptionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_notification_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyChannelSubscriptionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v4_notification_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyChannelSubscriptionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v4_notification_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v4_notification_proto_goTypes,
		DependencyIndexes: file_v4_notification_proto_depIdxs,
		MessageInfos:      file_v4_notification_proto_msgTypes,
	}.Build()
	File_v4_notification_proto = out.File
	file_v4_notification_proto_rawDesc = nil
	file_v4_notification_proto_goTypes = nil
	file_v4_notification_proto_depIdxs = nil
}
