// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: v4/pin.proto

package v4

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PinService_GetPins_FullMethodName   = "/v4.PinService/GetPins"
	PinService_CreatePin_FullMethodName = "/v4.PinService/CreatePin"
	PinService_GetPin_FullMethodName    = "/v4.PinService/GetPin"
	PinService_DeletePin_FullMethodName = "/v4.PinService/DeletePin"
)

// PinServiceClient is the client API for PinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PinServiceClient interface {
	// 指定したチャンネルのピン留めのリストを取得
	GetPins(ctx context.Context, in *GetPinsRequest, opts ...grpc.CallOption) (*GetPinsResponse, error)
	// メッセージをピン留め
	CreatePin(ctx context.Context, in *CreatePinRequest, opts ...grpc.CallOption) (*Pin, error)
	// ピン情報を取得
	GetPin(ctx context.Context, in *GetPinRequest, opts ...grpc.CallOption) (*Pin, error)
	// メッセージのピン留めを解除
	DeletePin(ctx context.Context, in *DeletePinRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type pinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPinServiceClient(cc grpc.ClientConnInterface) PinServiceClient {
	return &pinServiceClient{cc}
}

func (c *pinServiceClient) GetPins(ctx context.Context, in *GetPinsRequest, opts ...grpc.CallOption) (*GetPinsResponse, error) {
	out := new(GetPinsResponse)
	err := c.cc.Invoke(ctx, PinService_GetPins_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) CreatePin(ctx context.Context, in *CreatePinRequest, opts ...grpc.CallOption) (*Pin, error) {
	out := new(Pin)
	err := c.cc.Invoke(ctx, PinService_CreatePin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) GetPin(ctx context.Context, in *GetPinRequest, opts ...grpc.CallOption) (*Pin, error) {
	out := new(Pin)
	err := c.cc.Invoke(ctx, PinService_GetPin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) DeletePin(ctx context.Context, in *DeletePinRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, PinService_DeletePin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PinServiceServer is the server API for PinService service.
// All implementations must embed UnimplementedPinServiceServer
// for forward compatibility
type PinServiceServer interface {
	// 指定したチャンネルのピン留めのリストを取得
	GetPins(context.Context, *GetPinsRequest) (*GetPinsResponse, error)
	// メッセージをピン留め
	CreatePin(context.Context, *CreatePinRequest) (*Pin, error)
	// ピン情報を取得
	GetPin(context.Context, *GetPinRequest) (*Pin, error)
	// メッセージのピン留めを解除
	DeletePin(context.Context, *DeletePinRequest) (*EmptyResponse, error)
	mustEmbedUnimplementedPinServiceServer()
}

// UnimplementedPinServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPinServiceServer struct {
}

func (UnimplementedPinServiceServer) GetPins(context.Context, *GetPinsRequest) (*GetPinsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPins not implemented")
}
func (UnimplementedPinServiceServer) CreatePin(context.Context, *CreatePinRequest) (*Pin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePin not implemented")
}
func (UnimplementedPinServiceServer) GetPin(context.Context, *GetPinRequest) (*Pin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPin not implemented")
}
func (UnimplementedPinServiceServer) DeletePin(context.Context, *DeletePinRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePin not implemented")
}
func (UnimplementedPinServiceServer) mustEmbedUnimplementedPinServiceServer() {}

// UnsafePinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PinServiceServer will
// result in compilation errors.
type UnsafePinServiceServer interface {
	mustEmbedUnimplementedPinServiceServer()
}

func RegisterPinServiceServer(s grpc.ServiceRegistrar, srv PinServiceServer) {
	s.RegisterService(&PinService_ServiceDesc, srv)
}

func _PinService_GetPins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPinsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).GetPins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_GetPins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).GetPins(ctx, req.(*GetPinsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_CreatePin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).CreatePin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_CreatePin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).CreatePin(ctx, req.(*CreatePinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_GetPin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).GetPin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_GetPin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).GetPin(ctx, req.(*GetPinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_DeletePin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).DeletePin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_DeletePin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).DeletePin(ctx, req.(*DeletePinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PinService_ServiceDesc is the grpc.ServiceDesc for PinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v4.PinService",
	HandlerType: (*PinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPins",
			Handler:    _PinService_GetPins_Handler,
		},
		{
			MethodName: "CreatePin",
			Handler:    _PinService_CreatePin_Handler,
		},
		{
			MethodName: "GetPin",
			Handler:    _PinService_GetPin_Handler,
		},
		{
			MethodName: "DeletePin",
			Handler:    _PinService_DeletePin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v4/pin.proto",
}
