// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: v4/stamp.proto

package v4

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StampService_GetStamps_FullMethodName            = "/v4.StampService/GetStamps"
	StampService_CreateStamp_FullMethodName          = "/v4.StampService/CreateStamp"
	StampService_GetStamp_FullMethodName             = "/v4.StampService/GetStamp"
	StampService_EditStamp_FullMethodName            = "/v4.StampService/EditStamp"
	StampService_DeleteStamp_FullMethodName          = "/v4.StampService/DeleteStamp"
	StampService_GetStampStats_FullMethodName        = "/v4.StampService/GetStampStats"
	StampService_GetMyStampHistory_FullMethodName    = "/v4.StampService/GetMyStampHistory"
	StampService_GetStampPalettes_FullMethodName     = "/v4.StampService/GetStampPalettes"
	StampService_CreateStampPalette_FullMethodName   = "/v4.StampService/CreateStampPalette"
	StampService_GetStampPalette_FullMethodName      = "/v4.StampService/GetStampPalette"
	StampService_EditStampPalette_FullMethodName     = "/v4.StampService/EditStampPalette"
	StampService_DeleteStampPalette_FullMethodName   = "/v4.StampService/DeleteStampPalette"
	StampService_GetPaletteStamps_FullMethodName     = "/v4.StampService/GetPaletteStamps"
	StampService_ReplacePaletteStamps_FullMethodName = "/v4.StampService/ReplacePaletteStamps"
	StampService_RemovePaletteStamp_FullMethodName   = "/v4.StampService/RemovePaletteStamp"
)

// StampServiceClient is the client API for StampService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StampServiceClient interface {
	// スタンプリストを取得
	GetStamps(ctx context.Context, in *GetStampsRequest, opts ...grpc.CallOption) (*GetStampsResponse, error)
	// スタンプを作成
	CreateStamp(ctx context.Context, in *CreateStampRequest, opts ...grpc.CallOption) (*Stamp, error)
	// スタンプ情報を取得
	GetStamp(ctx context.Context, in *GetStampRequest, opts ...grpc.CallOption) (*StampWithThumbnail, error)
	// スタンプ情報を編集
	EditStamp(ctx context.Context, in *EditStampRpcRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// スタンプを削除
	DeleteStamp(ctx context.Context, in *DeleteStampRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// スタンプの統計情報を取得
	GetStampStats(ctx context.Context, in *GetStampStatsRequest, opts ...grpc.CallOption) (*StampStats, error)
	// スタンプ履歴を取得
	GetMyStampHistory(ctx context.Context, in *GetMyStampHistoryRequest, opts ...grpc.CallOption) (*GetMyStampHistoryResponse, error)
	// スタンプパレットのリストを取得
	GetStampPalettes(ctx context.Context, in *GetStampPalettesRequest, opts ...grpc.CallOption) (*GetStampPalettesResponse, error)
	// スタンプパレットを作成
	CreateStampPalette(ctx context.Context, in *PostStampPaletteRequest, opts ...grpc.CallOption) (*StampPalette, error)
	// スタンプパレット情報を取得
	GetStampPalette(ctx context.Context, in *GetStampPaletteRequest, opts ...grpc.CallOption) (*StampPalette, error)
	// スタンプパレットを編集
	EditStampPalette(ctx context.Context, in *EditStampPaletteRpcRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// スタンプパレットを削除
	DeleteStampPalette(ctx context.Context, in *DeleteStampPaletteRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// スタンプパレットのスタンプリストを取得
	GetPaletteStamps(ctx context.Context, in *GetPaletteStampsRequest, opts ...grpc.CallOption) (*GetPaletteStampsResponse, error)
	// スタンプパレットのスタンプのリストを編集
	ReplacePaletteStamps(ctx context.Context, in *ReplacePaletteStampsRpcRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// スタンプパレットからスタンプを削除
	RemovePaletteStamp(ctx context.Context, in *RemovePaletteStampRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type stampServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStampServiceClient(cc grpc.ClientConnInterface) StampServiceClient {
	return &stampServiceClient{cc}
}

func (c *stampServiceClient) GetStamps(ctx context.Context, in *GetStampsRequest, opts ...grpc.CallOption) (*GetStampsResponse, error) {
	out := new(GetStampsResponse)
	err := c.cc.Invoke(ctx, StampService_GetStamps_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stampServiceClient) CreateStamp(ctx context.Context, in *CreateStampRequest, opts ...grpc.CallOption) (*Stamp, error) {
	out := new(Stamp)
	err := c.cc.Invoke(ctx, StampService_CreateStamp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stampServiceClient) GetStamp(ctx context.Context, in *GetStampRequest, opts ...grpc.CallOption) (*StampWithThumbnail, error) {
	out := new(StampWithThumbnail)
	err := c.cc.Invoke(ctx, StampService_GetStamp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stampServiceClient) EditStamp(ctx context.Context, in *EditStampRpcRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, StampService_EditStamp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stampServiceClient) DeleteStamp(ctx context.Context, in *DeleteStampRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, StampService_DeleteStamp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stampServiceClient) GetStampStats(ctx context.Context, in *GetStampStatsRequest, opts ...grpc.CallOption) (*StampStats, error) {
	out := new(StampStats)
	err := c.cc.Invoke(ctx, StampService_GetStampStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stampServiceClient) GetMyStampHistory(ctx context.Context, in *GetMyStampHistoryRequest, opts ...grpc.CallOption) (*GetMyStampHistoryResponse, error) {
	out := new(GetMyStampHistoryResponse)
	err := c.cc.Invoke(ctx, StampService_GetMyStampHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stampServiceClient) GetStampPalettes(ctx context.Context, in *GetStampPalettesRequest, opts ...grpc.CallOption) (*GetStampPalettesResponse, error) {
	out := new(GetStampPalettesResponse)
	err := c.cc.Invoke(ctx, StampService_GetStampPalettes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stampServiceClient) CreateStampPalette(ctx context.Context, in *PostStampPaletteRequest, opts ...grpc.CallOption) (*StampPalette, error) {
	out := new(StampPalette)
	err := c.cc.Invoke(ctx, StampService_CreateStampPalette_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stampServiceClient) GetStampPalette(ctx context.Context, in *GetStampPaletteRequest, opts ...grpc.CallOption) (*StampPalette, error) {
	out := new(StampPalette)
	err := c.cc.Invoke(ctx, StampService_GetStampPalette_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stampServiceClient) EditStampPalette(ctx context.Context, in *EditStampPaletteRpcRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, StampService_EditStampPalette_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stampServiceClient) DeleteStampPalette(ctx context.Context, in *DeleteStampPaletteRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, StampService_DeleteStampPalette_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stampServiceClient) GetPaletteStamps(ctx context.Context, in *GetPaletteStampsRequest, opts ...grpc.CallOption) (*GetPaletteStampsResponse, error) {
	out := new(GetPaletteStampsResponse)
	err := c.cc.Invoke(ctx, StampService_GetPaletteStamps_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stampServiceClient) ReplacePaletteStamps(ctx context.Context, in *ReplacePaletteStampsRpcRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, StampService_ReplacePaletteStamps_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stampServiceClient) RemovePaletteStamp(ctx context.Context, in *RemovePaletteStampRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, StampService_RemovePaletteStamp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StampServiceServer is the server API for StampService service.
// All implementations must embed UnimplementedStampServiceServer
// for forward compatibility
type StampServiceServer interface {
	// スタンプリストを取得
	GetStamps(context.Context, *GetStampsRequest) (*GetStampsResponse, error)
	// スタンプを作成
	CreateStamp(context.Context, *CreateStampRequest) (*Stamp, error)
	// スタンプ情報を取得
	GetStamp(context.Context, *GetStampRequest) (*StampWithThumbnail, error)
	// スタンプ情報を編集
	EditStamp(context.Context, *EditStampRpcRequest) (*EmptyResponse, error)
	// スタンプを削除
	DeleteStamp(context.Context, *DeleteStampRequest) (*EmptyResponse, error)
	// スタンプの統計情報を取得
	GetStampStats(context.Context, *GetStampStatsRequest) (*StampStats, error)
	// スタンプ履歴を取得
	GetMyStampHistory(context.Context, *GetMyStampHistoryRequest) (*GetMyStampHistoryResponse, error)
	// スタンプパレットのリストを取得
	GetStampPalettes(context.Context, *GetStampPalettesRequest) (*GetStampPalettesResponse, error)
	// スタンプパレットを作成
	CreateStampPalette(context.Context, *PostStampPaletteRequest) (*StampPalette, error)
	// スタンプパレット情報を取得
	GetStampPalette(context.Context, *GetStampPaletteRequest) (*StampPalette, error)
	// スタンプパレットを編集
	EditStampPalette(context.Context, *EditStampPaletteRpcRequest) (*EmptyResponse, error)
	// スタンプパレットを削除
	DeleteStampPalette(context.Context, *DeleteStampPaletteRequest) (*EmptyResponse, error)
	// スタンプパレットのスタンプリストを取得
	GetPaletteStamps(context.Context, *GetPaletteStampsRequest) (*GetPaletteStampsResponse, error)
	// スタンプパレットのスタンプのリストを編集
	ReplacePaletteStamps(context.Context, *ReplacePaletteStampsRpcRequest) (*EmptyResponse, error)
	// スタンプパレットからスタンプを削除
	RemovePaletteStamp(context.Context, *RemovePaletteStampRequest) (*EmptyResponse, error)
	mustEmbedUnimplementedStampServiceServer()
}

// UnimplementedStampServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStampServiceServer struct {
}

func (UnimplementedStampServiceServer) GetStamps(context.Context, *GetStampsRequest) (*GetStampsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStamps not implemented")
}
func (UnimplementedStampServiceServer) CreateStamp(context.Context, *CreateStampRequest) (*Stamp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStamp not implemented")
}
func (UnimplementedStampServiceServer) GetStamp(context.Context, *GetStampRequest) (*StampWithThumbnail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStamp not implemented")
}
func (UnimplementedStampServiceServer) EditStamp(context.Context, *EditStampRpcRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditStamp not implemented")
}
func (UnimplementedStampServiceServer) DeleteStamp(context.Context, *DeleteStampRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStamp not implemented")
}
func (UnimplementedStampServiceServer) GetStampStats(context.Context, *GetStampStatsRequest) (*StampStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStampStats not implemented")
}
func (UnimplementedStampServiceServer) GetMyStampHistory(context.Context, *GetMyStampHistoryRequest) (*GetMyStampHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyStampHistory not implemented")
}
func (UnimplementedStampServiceServer) GetStampPalettes(context.Context, *GetStampPalettesRequest) (*GetStampPalettesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStampPalettes not implemented")
}
func (UnimplementedStampServiceServer) CreateStampPalette(context.Context, *PostStampPaletteRequest) (*StampPalette, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStampPalette not implemented")
}
func (UnimplementedStampServiceServer) GetStampPalette(context.Context, *GetStampPaletteRequest) (*StampPalette, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStampPalette not implemented")
}
func (UnimplementedStampServiceServer) EditStampPalette(context.Context, *EditStampPaletteRpcRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditStampPalette not implemented")
}
func (UnimplementedStampServiceServer) DeleteStampPalette(context.Context, *DeleteStampPaletteRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStampPalette not implemented")
}
func (UnimplementedStampServiceServer) GetPaletteStamps(context.Context, *GetPaletteStampsRequest) (*GetPaletteStampsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaletteStamps not implemented")
}
func (UnimplementedStampServiceServer) ReplacePaletteStamps(context.Context, *ReplacePaletteStampsRpcRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplacePaletteStamps not implemented")
}
func (UnimplementedStampServiceServer) RemovePaletteStamp(context.Context, *RemovePaletteStampRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePaletteStamp not implemented")
}
func (UnimplementedStampServiceServer) mustEmbedUnimplementedStampServiceServer() {}

// UnsafeStampServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StampServiceServer will
// result in compilation errors.
type UnsafeStampServiceServer interface {
	mustEmbedUnimplementedStampServiceServer()
}

func RegisterStampServiceServer(s grpc.ServiceRegistrar, srv StampServiceServer) {
	s.RegisterService(&StampService_ServiceDesc, srv)
}

func _StampService_GetStamps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStampsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StampServiceServer).GetStamps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StampService_GetStamps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StampServiceServer).GetStamps(ctx, req.(*GetStampsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StampService_CreateStamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StampServiceServer).CreateStamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StampService_CreateStamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StampServiceServer).CreateStamp(ctx, req.(*CreateStampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StampService_GetStamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StampServiceServer).GetStamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StampService_GetStamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StampServiceServer).GetStamp(ctx, req.(*GetStampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StampService_EditStamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditStampRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StampServiceServer).EditStamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StampService_EditStamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StampServiceServer).EditStamp(ctx, req.(*EditStampRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StampService_DeleteStamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StampServiceServer).DeleteStamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StampService_DeleteStamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StampServiceServer).DeleteStamp(ctx, req.(*DeleteStampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StampService_GetStampStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStampStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StampServiceServer).GetStampStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StampService_GetStampStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StampServiceServer).GetStampStats(ctx, req.(*GetStampStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StampService_GetMyStampHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyStampHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StampServiceServer).GetMyStampHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StampService_GetMyStampHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StampServiceServer).GetMyStampHistory(ctx, req.(*GetMyStampHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StampService_GetStampPalettes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStampPalettesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StampServiceServer).GetStampPalettes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StampService_GetStampPalettes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StampServiceServer).GetStampPalettes(ctx, req.(*GetStampPalettesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StampService_CreateStampPalette_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostStampPaletteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StampServiceServer).CreateStampPalette(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StampService_CreateStampPalette_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StampServiceServer).CreateStampPalette(ctx, req.(*PostStampPaletteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StampService_GetStampPalette_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStampPaletteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StampServiceServer).GetStampPalette(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StampService_GetStampPalette_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StampServiceServer).GetStampPalette(ctx, req.(*GetStampPaletteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StampService_EditStampPalette_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditStampPaletteRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StampServiceServer).EditStampPalette(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StampService_EditStampPalette_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StampServiceServer).EditStampPalette(ctx, req.(*EditStampPaletteRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StampService_DeleteStampPalette_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStampPaletteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StampServiceServer).DeleteStampPalette(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StampService_DeleteStampPalette_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StampServiceServer).DeleteStampPalette(ctx, req.(*DeleteStampPaletteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StampService_GetPaletteStamps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaletteStampsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StampServiceServer).GetPaletteStamps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StampService_GetPaletteStamps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StampServiceServer).GetPaletteStamps(ctx, req.(*GetPaletteStampsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StampService_ReplacePaletteStamps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplacePaletteStampsRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StampServiceServer).ReplacePaletteStamps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StampService_ReplacePaletteStamps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StampServiceServer).ReplacePaletteStamps(ctx, req.(*ReplacePaletteStampsRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StampService_RemovePaletteStamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePaletteStampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StampServiceServer).RemovePaletteStamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StampService_RemovePaletteStamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StampServiceServer).RemovePaletteStamp(ctx, req.(*RemovePaletteStampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StampService_ServiceDesc is the grpc.ServiceDesc for StampService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StampService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v4.StampService",
	HandlerType: (*StampServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStamps",
			Handler:    _StampService_GetStamps_Handler,
		},
		{
			MethodName: "CreateStamp",
			Handler:    _StampService_CreateStamp_Handler,
		},
		{
			MethodName: "GetStamp",
			Handler:    _StampService_GetStamp_Handler,
		},
		{
			MethodName: "EditStamp",
			Handler:    _StampService_EditStamp_Handler,
		},
		{
			MethodName: "DeleteStamp",
			Handler:    _StampService_DeleteStamp_Handler,
		},
		{
			MethodName: "GetStampStats",
			Handler:    _StampService_GetStampStats_Handler,
		},
		{
			MethodName: "GetMyStampHistory",
			Handler:    _StampService_GetMyStampHistory_Handler,
		},
		{
			MethodName: "GetStampPalettes",
			Handler:    _StampService_GetStampPalettes_Handler,
		},
		{
			MethodName: "CreateStampPalette",
			Handler:    _StampService_CreateStampPalette_Handler,
		},
		{
			MethodName: "GetStampPalette",
			Handler:    _StampService_GetStampPalette_Handler,
		},
		{
			MethodName: "EditStampPalette",
			Handler:    _StampService_EditStampPalette_Handler,
		},
		{
			MethodName: "DeleteStampPalette",
			Handler:    _StampService_DeleteStampPalette_Handler,
		},
		{
			MethodName: "GetPaletteStamps",
			Handler:    _StampService_GetPaletteStamps_Handler,
		},
		{
			MethodName: "ReplacePaletteStamps",
			Handler:    _StampService_ReplacePaletteStamps_Handler,
		},
		{
			MethodName: "RemovePaletteStamp",
			Handler:    _StampService_RemovePaletteStamp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v4/stamp.proto",
}
