// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: v4/webhook.proto

package v4

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WebhookService_GetWebhooks_FullMethodName          = "/v4.WebhookService/GetWebhooks"
	WebhookService_CreateWebhook_FullMethodName        = "/v4.WebhookService/CreateWebhook"
	WebhookService_GetWebhook_FullMethodName           = "/v4.WebhookService/GetWebhook"
	WebhookService_EditWebhook_FullMethodName          = "/v4.WebhookService/EditWebhook"
	WebhookService_DeleteWebhook_FullMethodName        = "/v4.WebhookService/DeleteWebhook"
	WebhookService_ChangeWebhookIcon_FullMethodName    = "/v4.WebhookService/ChangeWebhookIcon"
	WebhookService_GetWebhookSecret_FullMethodName     = "/v4.WebhookService/GetWebhookSecret"
	WebhookService_ReissueWebhookSecret_FullMethodName = "/v4.WebhookService/ReissueWebhookSecret"
	WebhookService_PostWebhookMessage_FullMethodName   = "/v4.WebhookService/PostWebhookMessage"
	WebhookService_GetWebhookStatistics_FullMethodName = "/v4.WebhookService/GetWebhookStatistics"
)

// WebhookServiceClient is the client API for WebhookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebhookServiceClient interface {
	// Webhookのリストを取得します。
	GetWebhooks(ctx context.Context, in *GetWebhooksRequest, opts ...grpc.CallOption) (*GetWebhooksResponse, error)
	// Webhookを新規作成します。
	CreateWebhook(ctx context.Context, in *PostWebhookRequest, opts ...grpc.CallOption) (*Webhook, error)
	// 指定したWebhookの情報を取得します。
	GetWebhook(ctx context.Context, in *GetWebhookRequest, opts ...grpc.CallOption) (*Webhook, error)
	// 指定したWebhookの情報を変更します。
	EditWebhook(ctx context.Context, in *EditWebhookRpcRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// 指定したWebhookを削除します。
	DeleteWebhook(ctx context.Context, in *DeleteWebhookRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// Webhookのアイコンを変更します。
	ChangeWebhookIcon(ctx context.Context, in *ChangeWebhookIconRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// Webhookのシークレットを取得します。
	GetWebhookSecret(ctx context.Context, in *GetWebhookSecretRequest, opts ...grpc.CallOption) (*GetWebhookSecretResponse, error)
	// Webhookのシークレットを再発行します。
	ReissueWebhookSecret(ctx context.Context, in *ReissueWebhookSecretRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// Webhookメッセージを投稿します。
	PostWebhookMessage(ctx context.Context, in *PostWebhookMessageRpcRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// Webhookの統計情報を取得します。
	GetWebhookStatistics(ctx context.Context, in *GetWebhookStatisticsRequest, opts ...grpc.CallOption) (*GetWebhookStatisticsResponse, error)
}

type webhookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebhookServiceClient(cc grpc.ClientConnInterface) WebhookServiceClient {
	return &webhookServiceClient{cc}
}

func (c *webhookServiceClient) GetWebhooks(ctx context.Context, in *GetWebhooksRequest, opts ...grpc.CallOption) (*GetWebhooksResponse, error) {
	out := new(GetWebhooksResponse)
	err := c.cc.Invoke(ctx, WebhookService_GetWebhooks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) CreateWebhook(ctx context.Context, in *PostWebhookRequest, opts ...grpc.CallOption) (*Webhook, error) {
	out := new(Webhook)
	err := c.cc.Invoke(ctx, WebhookService_CreateWebhook_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) GetWebhook(ctx context.Context, in *GetWebhookRequest, opts ...grpc.CallOption) (*Webhook, error) {
	out := new(Webhook)
	err := c.cc.Invoke(ctx, WebhookService_GetWebhook_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) EditWebhook(ctx context.Context, in *EditWebhookRpcRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, WebhookService_EditWebhook_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) DeleteWebhook(ctx context.Context, in *DeleteWebhookRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, WebhookService_DeleteWebhook_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) ChangeWebhookIcon(ctx context.Context, in *ChangeWebhookIconRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, WebhookService_ChangeWebhookIcon_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) GetWebhookSecret(ctx context.Context, in *GetWebhookSecretRequest, opts ...grpc.CallOption) (*GetWebhookSecretResponse, error) {
	out := new(GetWebhookSecretResponse)
	err := c.cc.Invoke(ctx, WebhookService_GetWebhookSecret_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) ReissueWebhookSecret(ctx context.Context, in *ReissueWebhookSecretRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, WebhookService_ReissueWebhookSecret_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) PostWebhookMessage(ctx context.Context, in *PostWebhookMessageRpcRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, WebhookService_PostWebhookMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) GetWebhookStatistics(ctx context.Context, in *GetWebhookStatisticsRequest, opts ...grpc.CallOption) (*GetWebhookStatisticsResponse, error) {
	out := new(GetWebhookStatisticsResponse)
	err := c.cc.Invoke(ctx, WebhookService_GetWebhookStatistics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebhookServiceServer is the server API for WebhookService service.
// All implementations must embed UnimplementedWebhookServiceServer
// for forward compatibility
type WebhookServiceServer interface {
	// Webhookのリストを取得します。
	GetWebhooks(context.Context, *GetWebhooksRequest) (*GetWebhooksResponse, error)
	// Webhookを新規作成します。
	CreateWebhook(context.Context, *PostWebhookRequest) (*Webhook, error)
	// 指定したWebhookの情報を取得します。
	GetWebhook(context.Context, *GetWebhookRequest) (*Webhook, error)
	// 指定したWebhookの情報を変更します。
	EditWebhook(context.Context, *EditWebhookRpcRequest) (*EmptyResponse, error)
	// 指定したWebhookを削除します。
	DeleteWebhook(context.Context, *DeleteWebhookRequest) (*EmptyResponse, error)
	// Webhookのアイコンを変更します。
	ChangeWebhookIcon(context.Context, *ChangeWebhookIconRequest) (*EmptyResponse, error)
	// Webhookのシークレットを取得します。
	GetWebhookSecret(context.Context, *GetWebhookSecretRequest) (*GetWebhookSecretResponse, error)
	// Webhookのシークレットを再発行します。
	ReissueWebhookSecret(context.Context, *ReissueWebhookSecretRequest) (*EmptyResponse, error)
	// Webhookメッセージを投稿します。
	PostWebhookMessage(context.Context, *PostWebhookMessageRpcRequest) (*EmptyResponse, error)
	// Webhookの統計情報を取得します。
	GetWebhookStatistics(context.Context, *GetWebhookStatisticsRequest) (*GetWebhookStatisticsResponse, error)
	mustEmbedUnimplementedWebhookServiceServer()
}

// UnimplementedWebhookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWebhookServiceServer struct {
}

func (UnimplementedWebhookServiceServer) GetWebhooks(context.Context, *GetWebhooksRequest) (*GetWebhooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWebhooks not implemented")
}
func (UnimplementedWebhookServiceServer) CreateWebhook(context.Context, *PostWebhookRequest) (*Webhook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWebhook not implemented")
}
func (UnimplementedWebhookServiceServer) GetWebhook(context.Context, *GetWebhookRequest) (*Webhook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWebhook not implemented")
}
func (UnimplementedWebhookServiceServer) EditWebhook(context.Context, *EditWebhookRpcRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditWebhook not implemented")
}
func (UnimplementedWebhookServiceServer) DeleteWebhook(context.Context, *DeleteWebhookRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWebhook not implemented")
}
func (UnimplementedWebhookServiceServer) ChangeWebhookIcon(context.Context, *ChangeWebhookIconRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeWebhookIcon not implemented")
}
func (UnimplementedWebhookServiceServer) GetWebhookSecret(context.Context, *GetWebhookSecretRequest) (*GetWebhookSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWebhookSecret not implemented")
}
func (UnimplementedWebhookServiceServer) ReissueWebhookSecret(context.Context, *ReissueWebhookSecretRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReissueWebhookSecret not implemented")
}
func (UnimplementedWebhookServiceServer) PostWebhookMessage(context.Context, *PostWebhookMessageRpcRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostWebhookMessage not implemented")
}
func (UnimplementedWebhookServiceServer) GetWebhookStatistics(context.Context, *GetWebhookStatisticsRequest) (*GetWebhookStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWebhookStatistics not implemented")
}
func (UnimplementedWebhookServiceServer) mustEmbedUnimplementedWebhookServiceServer() {}

// UnsafeWebhookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebhookServiceServer will
// result in compilation errors.
type UnsafeWebhookServiceServer interface {
	mustEmbedUnimplementedWebhookServiceServer()
}

func RegisterWebhookServiceServer(s grpc.ServiceRegistrar, srv WebhookServiceServer) {
	s.RegisterService(&WebhookService_ServiceDesc, srv)
}

func _WebhookService_GetWebhooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebhooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).GetWebhooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_GetWebhooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).GetWebhooks(ctx, req.(*GetWebhooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_CreateWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).CreateWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_CreateWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).CreateWebhook(ctx, req.(*PostWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_GetWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).GetWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_GetWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).GetWebhook(ctx, req.(*GetWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_EditWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditWebhookRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).EditWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_EditWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).EditWebhook(ctx, req.(*EditWebhookRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_DeleteWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).DeleteWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_DeleteWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).DeleteWebhook(ctx, req.(*DeleteWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_ChangeWebhookIcon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeWebhookIconRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).ChangeWebhookIcon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_ChangeWebhookIcon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).ChangeWebhookIcon(ctx, req.(*ChangeWebhookIconRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_GetWebhookSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebhookSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).GetWebhookSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_GetWebhookSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).GetWebhookSecret(ctx, req.(*GetWebhookSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_ReissueWebhookSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReissueWebhookSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).ReissueWebhookSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_ReissueWebhookSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).ReissueWebhookSecret(ctx, req.(*ReissueWebhookSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_PostWebhookMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostWebhookMessageRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).PostWebhookMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_PostWebhookMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).PostWebhookMessage(ctx, req.(*PostWebhookMessageRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_GetWebhookStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebhookStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).GetWebhookStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_GetWebhookStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).GetWebhookStatistics(ctx, req.(*GetWebhookStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebhookService_ServiceDesc is the grpc.ServiceDesc for WebhookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebhookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v4.WebhookService",
	HandlerType: (*WebhookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWebhooks",
			Handler:    _WebhookService_GetWebhooks_Handler,
		},
		{
			MethodName: "CreateWebhook",
			Handler:    _WebhookService_CreateWebhook_Handler,
		},
		{
			MethodName: "GetWebhook",
			Handler:    _WebhookService_GetWebhook_Handler,
		},
		{
			MethodName: "EditWebhook",
			Handler:    _WebhookService_EditWebhook_Handler,
		},
		{
			MethodName: "DeleteWebhook",
			Handler:    _WebhookService_DeleteWebhook_Handler,
		},
		{
			MethodName: "ChangeWebhookIcon",
			Handler:    _WebhookService_ChangeWebhookIcon_Handler,
		},
		{
			MethodName: "GetWebhookSecret",
			Handler:    _WebhookService_GetWebhookSecret_Handler,
		},
		{
			MethodName: "ReissueWebhookSecret",
			Handler:    _WebhookService_ReissueWebhookSecret_Handler,
		},
		{
			MethodName: "PostWebhookMessage",
			Handler:    _WebhookService_PostWebhookMessage_Handler,
		},
		{
			MethodName: "GetWebhookStatistics",
			Handler:    _WebhookService_GetWebhookStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v4/webhook.proto",
}
