// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: v4/websocket.proto

package v4

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WebSocketService_Connect_FullMethodName = "/v4.WebSocketService/Connect"
)

// WebSocketServiceClient is the client API for WebSocketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebSocketServiceClient interface {
	// Connect to the WebSocket stream
	// Client can send initial parameters if needed (e.g. auth token in metadata)
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (WebSocketService_ConnectClient, error)
}

type webSocketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebSocketServiceClient(cc grpc.ClientConnInterface) WebSocketServiceClient {
	return &webSocketServiceClient{cc}
}

func (c *webSocketServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (WebSocketService_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &WebSocketService_ServiceDesc.Streams[0], WebSocketService_Connect_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &webSocketServiceConnectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WebSocketService_ConnectClient interface {
	Recv() (*WsEvent, error)
	grpc.ClientStream
}

type webSocketServiceConnectClient struct {
	grpc.ClientStream
}

func (x *webSocketServiceConnectClient) Recv() (*WsEvent, error) {
	m := new(WsEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WebSocketServiceServer is the server API for WebSocketService service.
// All implementations must embed UnimplementedWebSocketServiceServer
// for forward compatibility
type WebSocketServiceServer interface {
	// Connect to the WebSocket stream
	// Client can send initial parameters if needed (e.g. auth token in metadata)
	Connect(*ConnectRequest, WebSocketService_ConnectServer) error
	mustEmbedUnimplementedWebSocketServiceServer()
}

// UnimplementedWebSocketServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWebSocketServiceServer struct {
}

func (UnimplementedWebSocketServiceServer) Connect(*ConnectRequest, WebSocketService_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedWebSocketServiceServer) mustEmbedUnimplementedWebSocketServiceServer() {}

// UnsafeWebSocketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebSocketServiceServer will
// result in compilation errors.
type UnsafeWebSocketServiceServer interface {
	mustEmbedUnimplementedWebSocketServiceServer()
}

func RegisterWebSocketServiceServer(s grpc.ServiceRegistrar, srv WebSocketServiceServer) {
	s.RegisterService(&WebSocketService_ServiceDesc, srv)
}

func _WebSocketService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConnectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WebSocketServiceServer).Connect(m, &webSocketServiceConnectServer{stream})
}

type WebSocketService_ConnectServer interface {
	Send(*WsEvent) error
	grpc.ServerStream
}

type webSocketServiceConnectServer struct {
	grpc.ServerStream
}

func (x *webSocketServiceConnectServer) Send(m *WsEvent) error {
	return x.ServerStream.SendMsg(m)
}

// WebSocketService_ServiceDesc is the grpc.ServiceDesc for WebSocketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebSocketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v4.WebSocketService",
	HandlerType: (*WebSocketServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _WebSocketService_Connect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v4/websocket.proto",
}
