// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go

// Package mock_channel is a generated GoMock package.
package mock_channel

import (
	context "context"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "github.com/golang/mock/gomock"
	model "github.com/traPtitech/traQ/model"
	repository "github.com/traPtitech/traQ/repository"
	channel "github.com/traPtitech/traQ/service/channel"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// ArchiveChannel mocks base method.
func (m *MockManager) ArchiveChannel(ctx context.Context, id, updaterID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveChannel", ctx, id, updaterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArchiveChannel indicates an expected call of ArchiveChannel.
func (mr *MockManagerMockRecorder) ArchiveChannel(ctx, id, updaterID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveChannel", reflect.TypeOf((*MockManager)(nil).ArchiveChannel), ctx, id, updaterID)
}

// ChangeChannelSubscriptions mocks base method.
func (m *MockManager) ChangeChannelSubscriptions(ctx context.Context, channelID uuid.UUID, subscriptions map[uuid.UUID]model.ChannelSubscribeLevel, keepOffLevel bool, updaterID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeChannelSubscriptions", ctx, channelID, subscriptions, keepOffLevel, updaterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeChannelSubscriptions indicates an expected call of ChangeChannelSubscriptions.
func (mr *MockManagerMockRecorder) ChangeChannelSubscriptions(ctx, channelID, subscriptions, keepOffLevel, updaterID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeChannelSubscriptions", reflect.TypeOf((*MockManager)(nil).ChangeChannelSubscriptions), ctx, channelID, subscriptions, keepOffLevel, updaterID)
}

// CreatePublicChannel mocks base method.
func (m *MockManager) CreatePublicChannel(ctx context.Context, name string, parent, creatorID uuid.UUID) (*model.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePublicChannel", ctx, name, parent, creatorID)
	ret0, _ := ret[0].(*model.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePublicChannel indicates an expected call of CreatePublicChannel.
func (mr *MockManagerMockRecorder) CreatePublicChannel(ctx, name, parent, creatorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePublicChannel", reflect.TypeOf((*MockManager)(nil).CreatePublicChannel), ctx, name, parent, creatorID)
}

// GetChannel mocks base method.
func (m *MockManager) GetChannel(ctx context.Context, id uuid.UUID) (*model.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannel", ctx, id)
	ret0, _ := ret[0].(*model.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannel indicates an expected call of GetChannel.
func (mr *MockManagerMockRecorder) GetChannel(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannel", reflect.TypeOf((*MockManager)(nil).GetChannel), ctx, id)
}

// GetChannelFromPath mocks base method.
func (m *MockManager) GetChannelFromPath(ctx context.Context, path string) (*model.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelFromPath", ctx, path)
	ret0, _ := ret[0].(*model.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannelFromPath indicates an expected call of GetChannelFromPath.
func (mr *MockManagerMockRecorder) GetChannelFromPath(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelFromPath", reflect.TypeOf((*MockManager)(nil).GetChannelFromPath), ctx, path)
}

// GetChannelPathFromID mocks base method.
func (m *MockManager) GetChannelPathFromID(ctx context.Context, id uuid.UUID) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelPathFromID", ctx, id)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetChannelPathFromID indicates an expected call of GetChannelPathFromID.
func (mr *MockManagerMockRecorder) GetChannelPathFromID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelPathFromID", reflect.TypeOf((*MockManager)(nil).GetChannelPathFromID), ctx, id)
}

// GetDMChannel mocks base method.
func (m *MockManager) GetDMChannel(ctx context.Context, user1, user2 uuid.UUID) (*model.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDMChannel", ctx, user1, user2)
	ret0, _ := ret[0].(*model.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDMChannel indicates an expected call of GetDMChannel.
func (mr *MockManagerMockRecorder) GetDMChannel(ctx, user1, user2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDMChannel", reflect.TypeOf((*MockManager)(nil).GetDMChannel), ctx, user1, user2)
}

// GetDMChannelMapping mocks base method.
func (m *MockManager) GetDMChannelMapping(ctx context.Context, userID uuid.UUID) (map[uuid.UUID]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDMChannelMapping", ctx, userID)
	ret0, _ := ret[0].(map[uuid.UUID]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDMChannelMapping indicates an expected call of GetDMChannelMapping.
func (mr *MockManagerMockRecorder) GetDMChannelMapping(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDMChannelMapping", reflect.TypeOf((*MockManager)(nil).GetDMChannelMapping), ctx, userID)
}

// GetDMChannelMembers mocks base method.
func (m *MockManager) GetDMChannelMembers(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDMChannelMembers", ctx, id)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDMChannelMembers indicates an expected call of GetDMChannelMembers.
func (mr *MockManagerMockRecorder) GetDMChannelMembers(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDMChannelMembers", reflect.TypeOf((*MockManager)(nil).GetDMChannelMembers), ctx, id)
}

// IsChannelAccessibleToUser mocks base method.
func (m *MockManager) IsChannelAccessibleToUser(ctx context.Context, userID, channelID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsChannelAccessibleToUser", ctx, userID, channelID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsChannelAccessibleToUser indicates an expected call of IsChannelAccessibleToUser.
func (mr *MockManagerMockRecorder) IsChannelAccessibleToUser(ctx, userID, channelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsChannelAccessibleToUser", reflect.TypeOf((*MockManager)(nil).IsChannelAccessibleToUser), ctx, userID, channelID)
}

// IsPublicChannel mocks base method.
func (m *MockManager) IsPublicChannel(ctx context.Context, id uuid.UUID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPublicChannel", ctx, id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsPublicChannel indicates an expected call of IsPublicChannel.
func (mr *MockManagerMockRecorder) IsPublicChannel(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPublicChannel", reflect.TypeOf((*MockManager)(nil).IsPublicChannel), ctx, id)
}

// PublicChannelTree mocks base method.
func (m *MockManager) PublicChannelTree(ctx context.Context) channel.Tree {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicChannelTree", ctx)
	ret0, _ := ret[0].(channel.Tree)
	return ret0
}

// PublicChannelTree indicates an expected call of PublicChannelTree.
func (mr *MockManagerMockRecorder) PublicChannelTree(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicChannelTree", reflect.TypeOf((*MockManager)(nil).PublicChannelTree), ctx)
}

// UnarchiveChannel mocks base method.
func (m *MockManager) UnarchiveChannel(ctx context.Context, id, updaterID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnarchiveChannel", ctx, id, updaterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnarchiveChannel indicates an expected call of UnarchiveChannel.
func (mr *MockManagerMockRecorder) UnarchiveChannel(ctx, id, updaterID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnarchiveChannel", reflect.TypeOf((*MockManager)(nil).UnarchiveChannel), ctx, id, updaterID)
}

// UpdateChannel mocks base method.
func (m *MockManager) UpdateChannel(ctx context.Context, id uuid.UUID, args repository.UpdateChannelArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChannel", ctx, id, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateChannel indicates an expected call of UpdateChannel.
func (mr *MockManagerMockRecorder) UpdateChannel(ctx, id, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChannel", reflect.TypeOf((*MockManager)(nil).UpdateChannel), ctx, id, args)
}

// Wait mocks base method.
func (m *MockManager) Wait() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Wait")
}

// Wait indicates an expected call of Wait.
func (mr *MockManagerMockRecorder) Wait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockManager)(nil).Wait))
}
