name: CI

on:
  # Validate on push for Renovate auto merge without PR
  push:
    branches:
      - 'master'
      - 'renovate/**'
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: "./go.mod"
      - run: go mod download
      - run: make traQ
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: traQ
          path: traQ
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: "./go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: v2.12.2
          args: '--timeout 10m0s'
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    services:
      mysql:
        image: mariadb:10.11.18@sha256:5a5c675881ef3fd1c1da9b0a3bfd6ee82edbe39cd9e32e06be18034c37235e0e
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: "./go.mod"
      - name: Run tests
        run: |
          export TRAQ_IMAGEMAGICK=`which convert`
          go test ./... -coverprofile=coverage.txt -race -shuffle=on -vet=off
        env:
          MARIADB_HOSTNAME: 127.0.0.1
          MARIADB_PORT: 3306
          MARIADB_USERNAME: root
          MARIADB_PASSWORD: password
      - name: Upload coverage data
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          files: ./coverage.txt
  tbls:
    name: TBLS
    runs-on: ubuntu-latest
    needs: [build]
    services:
      mysql:
        image: mariadb:10.11.18@sha256:5a5c675881ef3fd1c1da9b0a3bfd6ee82edbe39cd9e32e06be18034c37235e0e
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: traq
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: traQ
      - uses: k1low/setup-tbls@f25e3d013a596865b2db90dac7ee19e9f15b5780 # v1.4.0
        with:
          version: v1.94.5
      - run: |
          chmod +x ./traQ
          ./traQ migrate --reset
          tbls lint
        env:
          TRAQ_MARIADB_HOST: 127.0.0.1
          TRAQ_MARIADB_PORT: 3306
          TRAQ_MARIADB_USERNAME: root
          TRAQ_MARIADB_PASSWORD: password
          TRAQ_MARIADB_DATABASE: traq
          TBLS_DSN: 'mariadb://root:password@127.0.0.1:3306/traq'
