name: swagger-change

on:
  push:
    branches:
      - 'master'
    paths:
      - 'docs/v3-api.yaml'
      - '.github/workflows/swagger-change.yml'
  pull_request:
    paths:
      - 'docs/v3-api.yaml'
      - '.github/workflows/swagger-change.yml'

permissions:
  contents: read

jobs:
  spectral:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Run spectral
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/work" \
            -w /work \
            stoplight/spectral:6.15.1@sha256:b3d5a530f83c4a72df69e682c5ac928bc9821b5ca3c42529e81d926c80fa50ab \
            lint docs/v3-api.yaml --ruleset .spectral.yml --verbose
  node-traq:
    name: node-traq
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'traPtitech',
              repo: 'node-traq',
              workflow_id: 'release.yml',
              ref: 'master'
            })
  go-traq:
    name: go-traq
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'traPtitech',
              repo: 'go-traq',
              workflow_id: 'release.yaml',
              ref: 'master'
            })
  swift-traq:
    name: swift-traq
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'traPtitech',
              repo: 'swift-traq',
              workflow_id: 'release.yml',
              ref: 'main'
            })
  rust-traq:
    name: rust-traq
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'traPtitech',
              repo: 'rust-traq',
              workflow_id: 'regenerate.yml',
              ref: 'main'
            })
